README.md

in addition to Mac OS X build status

Add link to FreeBSD build status

---

configure.ac

The string comparison operator from test(1) is "=" and not "==" (single equals sign).
HTH,
-- khorben

Fixed a test operator mishap

---

libpkg/scripts.c

If the initial call fails, don't try to kill any child processes.
Also, always pkg_emit_errno() on any PROCCTL_REAP_KILL failure, not just for
errno==EINVAL.

Make sure the kernel allows PROCCTL_REAP_ACQUIRE.

---

libpkg/pkg_jobs.c
tests/frontend/rubypuppet.shin

Issue: https://github.com/freebsd/pkg/issues/574

print which package is a reason for direct depend change

---

scripts/periodic/411.pkg-backup.in

This will keep 7 by default, but allows for overriding via daily_backup_pkg_count.

Fix up the rotation of the pkg-backup periodic script

---

docs/pkg.conf.5
libpkg/pkg_config.c
src/pkg.conf.sample

Add a new configuration item to define custom HTTP User-Agent

---

src/query.c

Issue: freebsd/pkg/issues/1282

Use power of two suffixes for humanized output form

---

src/shlib.c

Issue: https://github.com/freebsd/pkg/issues/1299

don't allow more than one shlib for request

---

src/audit.c
src/convert.c

cleanup: both pkgdb_it_free() and pkg_free() handle NULL as argument.

---

src/utils.c

This and the similar query_tty_yesno() have a much-too-small 1k message buffer,
and silently truncate messages longer than that, including the [Y/n] prompt.
Use a 64k buffer and report truncation.
Repro:  `pkg install wireshark wireshark-qt5`
It seems like this should happen fairly frequently, and I don't know why it hasn't been seen/fixed before.

vquery_yesno():  fix silent message truncation

---

docs/pkg-repo.8

We haven't been distributing repo.sqlite for a very long time.

Belatedly document the files actually created by pkg repo nowadays.

---

libpkg/pkg_add.c

Fix fallback logic for chown/chmod syscalls.

---

libpkg/pkg_jobs.c
libpkg/pkg_jobs_universe.c
libpkg/pkg_solve.c
libpkg/private/pkg_jobs.h

* Fix repos pinning
* Fix repos selection procedure
* Fix logic to skip same packages in the universe
* Propagate reponame in solver rules
* Fix pkg upgrade detection

Bunch of solver fixes

---

libpkg/Makefile.am
libpkg/metalog.c
libpkg/pkg_add.c
libpkg/pkg_config.c
libpkg/private/pkg.h
tests/frontend/install.sh

METALOG support

---

libpkg/pkg_repo_create.c
libpkg/private/pkg_printf.h
libpkg/rsa.c
src/event.c

Fix compilation warnings by removing no longer used functions.

Remove unused functions

---

libpkg/pkg_add.c

The initial problem started with commit 4d53b1 which added the
AT_SYMLINK_NOFOLLOW flag to fchmodat function.  On Linux, the flag is
recognized but not implemented.  Setting the flag on Linux causes
ENOTSUP to return in every case, which issue #1431 reported.
The solution to add a second "fallback" attempt by calling fchmodat was
accepted, but I think it was not tested on a port that contained
symbolic links in the packing list.  It doesn't work for symbolic links.
fchmodat will follow the link and fail with ENOENT (file not found).
From my limited research, it's not possible to change file modes on
symbolic links on Linux -- not until AT_SYMLINK_NOFOLLOW is implemented.
Note that lchmod is not an option because it has not been implemented
on Linux, nor is it part of the POSIX standard. …

Another follow-up for issue #1431

---

libpkg/pkg_elf.c
libpkg/private/elf_tables.h

This is from Sylvain Garrigues from FreeBSD Bugzilla PR 222865

recognize armv7

---

scripts/install_deps.sh
tests/frontend/fingerprint.sh
tests/frontend/install.sh
tests/frontend/pkg.sh

Hopefully these will get fixed, but don't let them cause the build to fail for
now.

Disable long failing tests

---

docs/pkg-version.8
src/version.c

And update docs.
This is from:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=198899

make pkg version -r imply -R

---

docs/pkg.8

This is from:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=208656

Add reference to pkg-alias in pkg.8

---

docs/pkg.conf.5

Signed-off-by: Oliver Pinter <oliver.pinter@hardenedbsd.org>

document IGNORE_OSVERSION pkg.conf option

---

docs/pkg-rquery.8

Mostly mdoc formatting fixes.
I've also improved the description of the `%l` query pattern modifier.

Improve the pkg-rquery manual

---

libpkg/pkg_add.c
libpkg/pkg_ports.c

I noticed these while studying the source code.

Fix some typos

---

libpkg/utils.c

Improve the "Allow mismatch now?" message.

Improve the message.

---

libpkg/pkg_elf.c

This is sensible in case the rootdir is actually a sysroot of a different
arch/version; likely caller wanted to use the arch/version installed in the
rootdir instead of that of the host.

pkg_elf: try $rootdir/ABI_FILE and use it if it exists

---

docs/pkg-set.8
src/set.c

Fixes https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=207402

pkg-set: Update usage strings for -A and -v parameters

---

docs/pkg-create.8
docs/pkg-register.8
docs/pkg-rquery.8
docs/pkg-search.8
docs/pkg-shlib.8
docs/pkg-version.8
docs/pkg-which.8
docs/pkg.conf.5

fix typos in manuals in docs directory

fix typos in docs

---

libpkg/lua_scripts.c
libpkg/scripts.c

The WNOWAIT flag is a flag for waitid() and not waitpid(). This results in
an EINVAL return value on macOS and an infinite loop.
Add a new local variable should_waitpid instead to check if the return
status has already been captured.
After this change only two tests fail on macOS and it may also help for
other operating systems.

Fix child process handling in scripts.c and lua_scripts.c

---

tests/frontend/query.sh

tests/frontend/query.sh: remove debug code

---

libpkg/pkg_add.c

"Huh, why does it segfault?" :)
See commit descriptions.

Fix pkg-add's pkg_globmatch

---

docs/pkg-autoremove.8
src/autoremove.c
tests/frontend/autoremove.sh

While here also patch it to not just ignore invalid arguments.

autoremove: Add --no-scripts same as install and delete 

---

docs/pkg_repos.3

fix trivial typos in docs/pkg_repos.3

fix trivial typos in pkg_repos.3

---

docs/pkg-create.8
docs/pkg-keywords.5
docs/pkg-repo.8
docs/pkg-search.8
docs/pkg-updating.8
docs/pkg_printf.3

fix "style warning" by "mandoc -T lint" in docs

fix style warning

---

libpkg/pkg_solve.c

libpkg: Minor cleanup in pkg_solve.c

---

auto.def
compat/Makefile.autosetup
docs/Makefile.autosetup
external/blake2/Makefile.autosetup
external/libfetch/Makefile.autosetup
external/libucl/Makefile.autosetup
external/linenoise/Makefile.autosetup
external/msgpuck/Makefile.autosetup
external/picosat/Makefile.autosetup
external/sqlite/Makefile.autosetup
external/yxml/Makefile.autosetup
libpkg/Makefile.autosetup
libpkg/repo/binary/Makefile.autosetup
scripts/Makefile.autosetup
src/Makefile.autosetup

- Loads of VPATHs and new include flags.
- We need to make some directories in the build directory
- Some occasional confusion between the build directory and the source
directory for particular files' locations.

Support out-of-tree builds

---

src/audit.c

error in structured (raw) output

---

.gitignore
libpkg/pkg_jobs.c
libpkg/pkg_jobs_conflicts.c
libpkg/pkghash.c
libpkg/private/pkg.h
libpkg/private/pkg_jobs.h

Some more NFC patches that came out of some work on FreeBSD PR 263879. Mostly removing unused code and minor refactoring.

More minor cleanups in libpkg

---

tests/frontend/fingerprint.sh

See PR 2080 for an explanation.
Note, this change isn't complete. Either we should also fix pkg-repo docs, or find another way to handle the problem. I'm happy to work on it, but am not sure which direction to go.

Fix a flaky repo test

---

libpkg/pkgdb.c
tests/frontend/annotate.sh

`pkg annotate --modify` currently returns a fairly odd exitstatus; its exitstatus reflects whether the number of changed rows after its SQL query is 1.  But there are various cases with the existing SQL code where normal execution can return changed_rows != 1, and cases where errors can return changed_rows == 1.  Where this caused me trouble is that `pkg annotate --modify pkgname key val pkgname` returns exitcode 1 when an annotation with that key already exists.  When I dug into it, I found that the multiple-package case can return unexpected errors too.
The modify operation on the database is implemented as a delete, then an insert, reusing queries from other annotate operations.  There's not any serious practical problem with this, the queries are in a SQL transaction anyway, but it …

Give `pkg annotate --modify` a sensible exitstatus

---

docs/pkg.conf.5

Closes #2083.
Reported by: EHWV

Fix Xr to pkg-repository

---

docs/pkg-version.8

Closes #2091.
Reported by: KOIZUMI Satoru

pkg-version.8: Fix the use of Op

---

libpkg/fetch_libcurl.c

Historically, FETCH_TIMEOUT hasn't been hit unless the transfer isn't making process.
Switch to declaring a CONNECTTIMEOUT of FETCH_TIMEOUT and setup the low speed timeout instead.  By default, I've arbitrarily chosen 2 KB/s as the low threshold as that's pretty slow, but it could make sense to be a little more forgiving.

libpkg: more accurately implement FETCH_TIMEOUT with libpkg

---

libpkg/repo/binary/init.c

Motivated by the errors reported here: https://groups.google.com/g/syzkaller/c/Q9VZ71-siLc/m/syUv6j4sAgAJ

repo: Improve error messages

---

libpkg/pkg_jobs.c

This transitively enables cancelling during install/upgrade on the fetching stage too.

Support cancellation in pkg_jobs_fetch().

---

libpkg/pkg_delete.c

The cancellation happens after the current package finishes removing. This make the cancellation safe as pkg starts removing packages from leaves.

Add cancellation support for delete jobs.

---

src/check.c

Caught my eye when reading through the code.

check: fix printf format

---

libpkg/repo/binary/update.c

PR:  https://github.com/freebsd/pkg/issues/2200

update: lock globally and sync return of concurrent process

---

libpkg/sha256.c

See commit [message](https://github.com/freebsd/pkg/commit/d555f69af8636b90db669ca429733c47585c1fcd).

sha256.c: simplify byte reverse ordering and explicitly cast from unsigned long long to unsigned int

---

libpkg/backup.c
libpkg/utils.c
src/main.c

Please see the commit messages, listed below.
- https://github.com/freebsd/pkg/commit/7fc79fbc70d1cef52ce48173030169ec9bdf2f18
- https://github.com/freebsd/pkg/commit/3459d8d82ed7076407a2c1e201c3a52518481d4c
- https://github.com/freebsd/pkg/commit/4112dc8e5803516dba1dc327d3a1a550a8785a3e
- https://github.com/freebsd/pkg/commit/5d4db6314d18dac2a2b12a41ea26dd808cff252f
- https://github.com/freebsd/pkg/commit/bc34aeed2ef7228d7531b76ad36297e41e35758b

Apply a series of patches for a few things

---

compat/bsd_compat.h
libpkg/pkg_audit.c
libpkg/pkg_macho.c
libpkg/pkg_sandbox.c
libpkg/private/pkg.h
libpkg/scripts.c

Please see the commit messages, [1](https://github.com/freebsd/pkg/commit/a2e4c1de44903586999b2d3e553c0ef7563a4aec) and [2](https://github.com/freebsd/pkg/commit/8db0164d0dc891d6e28123162e40c2a33a6be169).

pkg: fix glibc build, use nitems(), and a few tiny things

---

libpkg/fetch_libcurl.c
libpkg/fetch_libfetch.c
src/add.c
src/alias.c
src/upgrade.c
src/version.c

Please see the commit messages.
1. https://github.com/freebsd/pkg/commit/8afa18197cf102ff4b061f611a9aba74895a45f8
2. https://github.com/freebsd/pkg/commit/4b7d66025ae4aa070495fe3d3cc21259ece666ce

cleanup: use fputc, goto, and a few others

---

libpkg/pkg_macho.c
src/create.c

Please see the commit messages for complete descriptions.
1. https://github.com/freebsd/pkg/commit/93e9277ee43be45a94b42d0d123e96f316b36d30
2. https://github.com/freebsd/pkg/commit/cdcd03882fe9418656d332709cf7fa86350cfbd5

pkg_macho.c, create.c: fix and cleaned up a few things

---

libpkg/elfhints.c

See the rationale for this change in https://reviews.freebsd.org/D44053
Since the pkg command reads and writes the hints file, it must be able to adapt the byte-order used, which will become little-endian on all architectures in -CURRENT (if the review is approved). STABLE releases will continue to use the native byte order for some time.
The proposed change to the pkg command makes it detect the byte-order of an existing hints file.
If no hints file exists, the native byte-order will be created (as before).
When the default has been changed to little-endian in all supported versions of FreeBSD on powerpc64 (and possible further big-endian architectures), the pkg command should be adjusted to also always create a little-endian hints file.
(There are 2 older commits in this pull-request …

Prepare pkg command for little-endian ld-elf.so.hints on all archictectures

---

src/version.c

Please see the commit message for details.
https://github.com/freebsd/pkg/commit/b0d7390832856aa53a743a017db86e60b19a2024

src/version.c: add proper return codes for package queries

---

README.md
libpkg/elfhints.c
src/delete.c
src/event.c
src/utils.c

Commits
src/utils.c: https://github.com/freebsd/pkg/commit/45d156463dab747b9870015ca9a260d105d71cfd
src/delete.c: https://github.com/freebsd/pkg/commit/428d73d83594edca3e3cfd48df6121ba7bf1e4df
src/event.c: https://github.com/freebsd/pkg/commit/1769e0faec503030ddeb0d5fdd6da9a9184a4870
libpkg/elfhints.c: https://github.com/freebsd/pkg/commit/2450e256c3e719382ae67355fd62866a418a389f
README.md: https://github.com/freebsd/pkg/commit/b624f13aa06268e73cd7f6a963f6e778050f7042

Use putchar() for a single character, and README typos

---

libpkg/pkg_audit.c
libpkg/pkg_elf.c
libpkg/pkg_macho.c
libpkg/pkgdb.c
libpkg/repo/binary/common.c
libpkg/repo/binary/query.c
libpkg/utils.c

Commit messages:
1. 5c2c6d92f9fc6d99e0f314f80623ee331f162c91
2. f09eac161a061f314c8ac95b4c5cb808e70648b0
3. c3651589cdd2a82de2000d0d0e35a083597472be
4. c270dcea89a75f3dd807eb30078b674104bf2e58
5. 75be78e43c1a388d1af3d8d2ae3a11cb901b23d1
6. 4d4682ee419a966624dfdd514a0c5ce5922fc3e4

libpkg/*: cleanup a few things, and use memset over bzero

---

libpkg/repo/binary/common.c
libpkg/repo/binary/init.c
libpkg/repo/binary/update.c

repos: fix database path handling when PKG_DBDIR is overridden

---

tests/frontend/pubkey.sh

Switch to using new_pkg() and check the contents of the repo

Improve the pubkey tests

---

tests/frontend/updating.sh

1) I am not sure if switching to use new_pkg() is worth it here with the UPDATING change.. Thoughts?
2) Changing the filename of the pkg ucl is probably worth it for doing parallelism in the future, but can do that separately if 1 does not go in.

Improve updating tests

---

libpkg/packing.c

The cases here may return ARCHIVE_WARN when the necessary libfoo isn't
available, indicating that it's going to shell out to satisfy the
request.  We can't necessarily cope with shelling out, as that may be
incompatible with a sandbox.
Erroring out gives us a path to realizing that the providing libarchive
is broken.

libpkg: fail on ARCHIVE_WARN

---

docs/pkg-repository.5

pkg-repository.5 Latest/ May contain (singular)

---

auto.def
external/Makefile.autosetup
libpkg/Makefile.autosetup
libpkg/repo/binary/Makefile.autosetup
src/Makefile.autosetup

- **Allow to build with external libcurl**
- **Fix external libarchive support**

Fix pkg build with external libraries

---

tests/lib/lua.c

lua:print_msg unit test fails on recent Ubuntu/MacOS failing to compare the testfile (Cannot open testfile). The issue is with the inappropriate call to open(O_CREATE) which mandates a third mode argument. If unspecified the mode of the file is a random number from the stack and might be lacking read permission for the subsequent comparison to succeed.
While here added ATF checks for open/close.
This closes the last remaining kyua failure on Ubuntu 24.04.

Fix kyua tests/lua:print_msg on Ubuntu 24.04 and MacOS.

---

libpkg/private/pkg_jobs.h

I found this commit lying around locally, looks like I forgot to include it in #2330.

libpkg: clarify documentation of pkg_solved->items

---

libpkg/pkg_create.c
src/updating.c

Three more low-hanging fruits from the LeakSanitizer logs.

Fix memory leaks

---

libpkg/pkg_add.c
libpkg/pkg_ports.c
libpkg/pkg_repo_create.c
libpkg/pkg_repo_meta.c
libpkg/pkgdb.c
src/event.c
src/repo.c

More leaks detected by LeakSanitizer.

Yet more small leaks.

---

libpkg/pkg_repo_create.c

popen(3) on Linux creates a unidirectional pipe whilst on FreeBSD a bi-directional. Follow the previously applied approach [1] to replace popen() calls with process_spawn_pipe() that creates two unidirectional pipes and creates a process using fork(2) and execve(2).
[1] https://github.com/freebsd/pkg/commit/c1be57ad058acf1ecf82deb327a5092228951f13

pkg-repo: avoid using a bi-directional pipe

---

libpkg/pkg_repo_create.c

Before the switch to threaded repo creation, file locks and unbuffered writes were used to prevent interleaved output.  Now that it's all threaded and the critical section is protected by a mutex, remove the remaining flock calls and switch to stdio.  Removes thousands of write() syscalls and saves ~8 seconds of CPU time on my system.
There is no fopenat() function, so the openat() calls are left in place but fdopen() is called on the results and the FILE* it returns is used after that.

pkg-repo: use buffered stdio to write output files

---

libpkg/pkg_elf.c

This is untested, but I'm pretty confident it should fix the bug described in #pkg on IRC.
@bapt is there a bugzilla bug report I should link to here?

libpkg: Fall back to ELF header for shlib OS

---

docs/pkg.8

pkg.8: add -o options to synopsis

---

docs/pkg-lua-script.5
external/libecc/src/arithmetic_tests/arithmetic_tests.c
external/libecc/src/sig/sig_algs.c
external/libucl/include/ucl.h
external/sqlite/shell.c
libpkg/fetch_libcurl.c

This one seems worth a PR for consistency

tidy spelling

---

libpkg/pkg_jobs.c
libpkg/pkgdb_iterator.c
libpkg/pkgdb_query.c
libpkg/repo/binary/query.c

Just a few small commits I made while reading the upgrade job code and trying to improve BACKUP_LIBRARIES.

Small cleanups
