freebsd/pkg

libpkg/repo/binary/fetch.c, libpkg/repo/binary/query.c
I think this fix will prevent issue (for example) when while fetching package it was interrupted (Ctrl^C) and as in result truncated.
Such scenario is easy repeatable. For example #1149 must be fixed after this patch.
Please review and merge if you are fine with it.
Before patch:
```
root@pkgtest:~/pkg # ./src/pkg-static install perl5
Updating FreeBSD repository catalogue...
FreeBSD repository is up-to-date.
Updating pd10 repository catalogue...
pd10 repository is up-to-date.
All repositories are up-to-date.
The following 1 packages will be affected (of 0 checked):
New packages to be INSTALLED:
perl5: 5.18.4_11 [FreeBSD]
The process will require 49 MiB more space.
13 MiB to be downloaded.
Proceed with this action? [y/N]: y
Fetching perl5-5.18.4_11.txz:  35%    5 MiB   2.2MB/s    00:04 …
```
=> Fixed issue with a cached packages which have a wrong size someway.

libpkg/pkg_add.c
When the PKG_ADD_FORCE_MISSING flag is set, we should ignore missing dependencies even when we have no directory to search for them in.
=> Fix 'pkg add -M -'.

libpkg/backup.c, libpkg/pkg.h.in, libpkg/pkg_add.c, libpkg/pkg_jobs.c, libpkg/pkg_ports.c, libpkg/pkg_solve.c, libpkg/pkgdb.c, libpkg/private/pkg.h, libpkg/repo/binary/update.c, src/check.c, src/utils.c
The only one left is `pkg_checksum_get_type()` in `pkg_checksum.c` but this one is a work in progress as per @bapt .
=> Fix a bunch of 'unused parameter' warnings

libpkg/private/elf_tables.h
NetBSD has no support for ARM's 64-bit platform yet; this therefore fixes building on NetBSD.
=> Not every platform supports aarch64 yet

libpkg/pkg_status.c
On platforms other than FreeBSD LOCALBASE may have to be different by default - like "/usr/pkg" on NetBSD with pkgsrc. This change lets the _LOCALBASE pre-processing variable be easily overridden at compile-time through the CPPFLAGS.
=> Let the default LOCALBASE variable be overridden at compile-time

src/pkgcli.h
before:
```
perl5-5.18.4_11: Add annotation tagged: foo with value: bar? [y/N]: y
6071772925249143647perl5-5.18.4_11: Cannot add annotation tagged: foo
```
after:
```
perl5-5.18.4_11: Add annotation tagged: foo with value: bar? [y/N]: y
pkg-static: perl5-5.18.4_11: Cannot add annotation tagged: foo
```
But also we can remove usage of getprogname() from pkg_warnx, but i'm not sure about compatibility.
=> fix pkg_warnx macro

libpkg/pkg_jobs.c, libpkg/pkg_solve.c
https://github.com/freebsd/pkg/commit/eabd4fb09077dbf6bb511193c02c4617987115a0 introduced new behaviour and this part was missed and don't work as expected from visual point of view.
```
cannot install package postgresql92-client, remove it from request? [Y/n]: [Y/n]: 
```
=> prevent double output for yes/no

docs/pkg-delete.8
Patch pkg-delete(8) to correct explanation of behaviour if it would leave other packages with unresolved dependencies
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=194981
=> PR194981: Patch pkg-delete(8) to correct explanation if unresolved dependencies

libpkg/pkg_add.c, libpkg/pkg_delete.c
This allows me to build pkg's master branch on NetBSD. I believe it is a more portable way to support platforms without UF_NOUNLINK/SF_NOUNLINK (like MacOS X was apparently found to be already).
=> Portability fix for UF_NOUNLINK

src/utils.c
Issue: https://github.com/freebsd/pkg/issues/1223
lme@ currently testing this patch. Please commit after his feedback in ticket.
=> Restore message about packages size to be downloaded

docs/pkg-info.8
Reported to me by Riccardo Torrini <riccardo@torrini.org>
=> Fix typo in pkg-info(8) man page

src/alias.c
as no agruments are actually printed
=> For `pkg alias -l` do not print ARGUMENTS header

src/audit.c
Add a second newline to leave a complete blank line after printing dependencies. It should make it easier to read as it currently runs into the next entry:
```
libtasn1-4.2 is vulnerable:
libtasn1 -- stack-based buffer overflow in asn1_der_decoding
CVE: CVE-2015-2806
WWW: http://vuxml.FreeBSD.org/freebsd/82595123-e8b8-11e4-a008-047d7b492d07.html
Packages that depend on libtasn1: p11-kit, gnutls, glib-networking, libsoup, libsoup-gnome, gvfs, Thunar, xfce4-desktop, xfce, ffmpeg, audacity
chromium-40.0.2214.115 is vulnerable:
```
There should be a space between the Packages and chromium lines, which this patch aims to solve
=> pkg audit -r formatting

libpkg/pkg_audit.c
This is a reduced version of my previous pull request and makes pkg audit to give https://vuxml.f.o results, as it's intended for human consumption.
=> Use https when showing audit result from vuxml.

libpkg/pkg.c
The PKG_LICENSE_LOGIC and PKG_REASON cases in pkg_vset() should
apparently access the corresponding field as in pkg_vget().
=> Fix two typos in pkg_vset(), to correspond to pkg_vget()'s code

libpkg/pkg_manifest.c
Currently, if pkg-message contains %, it would become %25 in the resulting package created by pkgng (ports/202343).
Looking at the code, we do an urlencode() when storing package description and message, but only do urldecode() when retrieving package description, not message.  The proposed patch would add the required decode for package message.
=> urldecode message when reading it back.

libpkg/pkgdb_query.c
pkg_jobs_universe_handle_provide can call pkg_jobs_universe_process_item which required pkg->digest to be loaded. That should fix issue with digest == NULL.
P.S. don't merge without review
=> load manifestdigest for pkgdb_query_shlib_provide

.travis.yml, configure.ac, libpkg/dns_utils.c, libpkg/pkg_config.c, scripts/travis_build.sh
This change allows the glibc/linux build to take advantage
of the non-ldns path in dns_utils.c by making res_setservers
optional (this is not available in glibc) and automatically
detecting the need to -lresolv.
=> Allow glibc/linux to build without libldns

configure.ac
Compiling without libbsd is not possible on linux (e.g. optreset
is missing when compiling main.c).  When libbsd is missing fail
at configure time rather than hitting compile errors.
=> Make libbsd a requirement on linux

external/Makefile.am
native-elf-format.h is auto-generated in the build tree
but only the source tree was on the include path.
Repro steps: "cd build_dir && $(SRC_DIR)/configure && make"
=> Fix out-of-tree build of libelf

libpkg/pkg_add.c
Without this fix, pkg appends random garbage to files with the @config tag.
=> Fix corruption with @config files due to a c-string vs buffer error.

libpkg/pkg_jobs_universe.c, libpkg/pkg_solve.c
Previously, we could replace already added provide with a new one. That caused memory leaks and broken upgrades when local provides were different from the remote ones. Namely, this should fix jpeg->jpeg-turbo upgrade.
=> Fix issue with provides searching.

docs/pkg.8
Just a small documentation change I thought about while reading the man page.
=> Remove reference to EOL FreeBSD version.

README.md
Update the OpenBSD README instructions to use https://github.com/freebsd/pkg, as the OpenBSD patches have been merged.
=> Update the OpenBSD README instructions to use this repository.

libpkg/packing.c
Signed-off-by: Chris Lamb <chris@chris-lamb.co.uk>
=> Correct environement -> environment typo

README.md
When scanning the README, in case one is unaware that pkg is a FreeBSD project, it's easy to miss FreeBSD in the URL of the GitHub repository and in the title of this document and to then think that pkg is not supported on FreeBSD.
=> List FreeBSD as one of the systems fully supported

libpkg/pkg.c
If it's not present revert to earlier behavior - non-atomic dup().
=> FreeBSD before 9.2 does not have F_DUPFD_CLOEXEC

libpkg/pkg_jobs.c
Print warning during pkg-delete if delete pattern doesn't match any packages. It's not an error and pkg continues normally.
=> Fix #1220: show warning if pkg-delete pattern doesn't match any package

src/event.c
Most of this patch has been run in DPorts for a year now.  It works well
and subjectively the alignment makes it much easier to absorb the
information as its dynamically updated.
Here's an example of the current behavior:
```
Fetching minecraft-client-1.7.9_4.txz: 100%  259 KiB 265.3kB/s    00:01
Fetching lwjgl-2.9.3.txz: 100%    1 MiB 761.9kB/s    00:02
Fetching jinput-20110801.r247.txz: 100%  191 KiB 195.4kB/s    00:01
Fetching openjdk8-8.102.14_1.txz: 100%   56 MiB   4.0MB/s    00:15
Fetching libXt-1.1.5,1.txz: 100%  450 KiB 460.7kB/s    00:01
Fetching xproto-7.0.28.txz: 100%   58 KiB  59.7kB/s    00:01
Fetching libSM-1.2.2_3,1.txz: 100%   22 KiB  22.8kB/s    00:01
Fetching libICE-1.0.9_1,1.txz: 100%   90 KiB  92.3kB/s    00:01
Fetching libX11-1.6.4,1.txz: 100%    2 MiB   1.7MB/s …
```
=> Align fetching progress bars

libpkg/pkg.h.in, libpkg/pkg_elf.c
Previously the ABI on NetBSD was reported as "NetBSD:7000:amd64"
Now pkg -vv returns:
ABI = "NetBSD:7:amd64"
ALTABI = "NetBSD:7:x86_64"
This also fixes the "Major OS version upgrade detected" warning that
NetBSD has been suffering from since the beginning.  Note that
development branches like 7.99 should return "NetBSD:8:amd64" for the
ABI.
=> Fix NetBSD ABI and suppress major version change warning

libpkg/elfhints.c, libpkg/private/ldconfig.h
The ELF hints on NetBSD are optionally located at /var/run/ld.so.hints.
If this file doesn't exist, pkg(8) fails (it should check for it rather
than assume it's there).
However, when this file is touched to create a blank version, pkg(8)
segfaults.  Until support for ELF hints is confirmed to work as it does
on FreeBSD and DragonFly, disable the functionality.
=> Disable ELF hint checking on NetBSD for now

libpkg/elfhints.c
It is believed that only these two platforms can leverage them.
It's better to specify the valid platforms rather than exclude the rest.
=> Explicitly limit ELF hints to DragonFly and FreeBSD

external/libfetch/ftp.c, external/libfetch/http.c
The funopen and vasprintf functions are filtered out during <stdio.h>
inclusion on NetBSD unless the _NETBSD_SOURCE macro is defined earlier.
This solves a preplexing segfault on NetBSD.  The funopen function would
be implicitly defined due to the lack of a prototype and the return type
default to an integer, resulting in an invalid pointer to the FILE
structure.
=> Solve segfault on fetching for NetBSD

src/pkg.conf.sample
This default is similar to prime-list except that it displays the
packages' origin instead of their names.  It is useful for synth and
poudriere users to generate repository build lists.
=> Define new default alias "prime-origins"

src/version.c
Issue: https://github.com/freebsd/pkg/issues/1503
=> pkg version with remote repo must use pkgname for -n instead of hardcoded origin

libpkg/pkg_jobs.c
Issue: https://github.com/freebsd/pkg/issues/1504
=> autoremove must don't take vital packages into account

libpkg/pkgdb_iterator.c
Currently, multiple packages queried with:
query '%n %L'
will output packages on multiple lines, skewing counts with "wc -l".  Instead,
aggregate all of the licenses of a package and output that.
Additionally, handle printing packages with no license information by using an
empty string.
Fixes #1510
=> query: aggregate license information

configure.ac
Until automake fix this upstream, for now, set the ARFLAGS variable to the
default values.  Silences the following:
ar: `u' modifier ignored since `D' is the default (see `U')
=> configure.ac: silence default warnings from ar(1)

configure.ac
Previously if CFLAGS contained -Wno-error that would override the
-Werror required for this configure test to work correctly.
Issue #1522
=> configure: append -Werror to CFLAGS (don't prepend)

scripts/periodic/410.pkg-audit.in
Due to missing quotes, both the expiration and deprecation reports
produce a single line, making the output painful to read:
```
Checking for packages with security vulnerabilities:
Database fetched: dim.  8 janv. 2017 04:12:38 CET
p5-Net-SMTP-SSL-1.04: Tag: expiration_date Value: 2017-03-31 puppet38-3.8.7_1: Tag: expiration_date Value: 2017-02-05
p5-Net-SMTP-SSL-1.04: Tag: deprecated Value: Deprecated by upstream, use Net::SMTP instead puppet38-3.8.7_1: Tag: deprecated Value: Upstream support ended, see http://tinyurl.com/puppet3eol
```
This patch improves this point:
```
Checking for packages with security vulnerabilities:
Database fetched: dim.  8 janv. 2017 04:12:38 CET
p5-Net-SMTP-SSL-1.04: Tag: expiration_date Value: 2017-03-31
puppet38-3.8.7_1: Tag: expiration_date Value: …
```
=> Fix pkg audit output

scripts/completion/_pkg.in
Commands such as `pkg -j jname info` should tab-complete packages as
installed in the jail `jname`, not as installed in the current context.
=> Propagate jail to Zsh completion invocations

libpkg/pkg_delete.c
While the check is understandable, it may lead to situations where
plugin-like files may linger in the system, causing problems.  We
have @sample for config files that takes care of this now.
=> pkg-delete: do not leave modified files behind

docs/pkg-install.8
This is the only mismatch for any -C/-i option across all man pages.
=> Fix typo in pkg-install man page.

src/which.c
The -g flag supposed to enable glob patterns in package search was broken since d7c19100db11dd341972dda371d233a1613dea03. This PR fixes it.
=> When the glob bool was true, the pattern was not pushed into patterns kv

libpkg/pkgdb.c
This addresses #1552, that pkg fails to open it's local database if it happens to be executed from a directory where it does not have read permissions.
I've built 1.10.0 from src with all optimizations off, and the root cause seems to be:
* sqlite3.c:35434,  unixFullPathname (see stacktrace below)
* calls `osLstat(zIn, &buf)` which fails
* zIn is "local.sqlite"
* osLstat is aSyscall[27].pCurrent (which is not overriden)
https://github.com/freebsd/pkg/blob/1.10.0/libpkg/pkgdb.c#L1008 overrides a few syscalls, but not lstat.
With the update to sqlite 3.15.2 the unixFullPathname implementation changed to now use lstat.
In addition the _dbdir_* VFS calls seems to fail for paths without a / (i.e. "local.sqlite"), the `strrchr("local.sqlite", '/')` would just return NULL and thats probably not …
=> Fix sqlite3 path lookup

scripts/periodic/410.pkg-audit.in
Also, remove the old check for interactive use.  It never worked, since
periodic(8) closes stdin.
See https://svnweb.freebsd.org/changeset/base/316342 for reference
=> 410.pkg-audit should use anticongestion on FreeBSD 12

src/clean.c
It means the cache is already clean.
=> pkg-clean: don't emit error on missing directory #1560

README.md, external/libucl/doc/lua_api.md
GitHub changed the way Markdown headings are parsed, so this change fixes it.
See [bryant1410/readmesfix](https://github.com/bryant1410/readmesfix) for more information.
Tackles bryant1410/readmesfix#1
=> Fix broken headings in Markdown files

src/utils.c
As setuid will set the effective user ID as well as the real user ID, it
is redundant to have to calls to set these IDs.  In the case of Linux,
it is illegal.  Once the effective ID is changed from "root" to
"nobody", pkg(8) no longer has the privilege to run setuid, resulting in
an "Operation not permitted" error when "sudo pkg" is executed.
Similarly, setegid is unnecessary when followed by setgid, but that is
legal.  Remove both redundant steps to fix operation on the Linux
platform and fix a spelling error while here.
=> Fix drop_privileges() on Linux

libpkg/pkg_elf.c
* This code was preventing shlibs_provided and shlibs_required entries
from being put in newly created packages on non-FreeBSD systems
* Also remove the no-longer used is_old_freebsd_armheader() function
* This commit should fix issue #1578
=> pkg_elf.c: remove bogus check for ELFOSABI_FREEBSD

libpkg/pkg_repo.c
pkg_repo_load_fingerprints_from_path() attempts to read all files on
path using pkg_repo_load_fingerprint(). When a file is empty
ucl_parser_get_object() will return NULL and the attempt to access
obj->type crashes pkg
It's simply to reproduce just following these steps:
```
Updating FreeBSD repository catalogue...
Fetching meta.txz: 100%    944 B   0.9kB/s    00:01
Fetching packagesite.txz: 100%    6 MiB   1.2MB/s    00:05
Processing entries: 100%
FreeBSD repository update completed. 26418 packages processed.
All repositories are up to date.
Updating FreeBSD repository catalogue...
Fetching meta.txz: 100%    944 B   0.9kB/s    00:01
Child process pid=67210 terminated abnormally: Segmentation fault
Updating FreeBSD repository catalogue...
Fetching meta.txz: 100%    944 B   0.9kB/s …
```
=> Silently return when obj is NULL

libpkg/pkg_elf.c, libpkg/private/elf_tables.h
The logic on the ELF note parsing was incorrect.  It happens to work
on *BSD, but the issue shows on other platforms (e.g. Linux ABI gets
set to "GNU:0").
The first mistake is assuming the note always has a namespace and that
this namespace equals the standard name of the operating system.  In
fact, having a namespace is not even required as there are default
definitions for tags: NT_VERSION (=1) and NT_ARCH (=2).
The BSDs (at least FreeBSD, DragonFly, and NetBSD) define their
own namespace (aka "Owner" on readelf" and the NT_VERSION tag, which
is a single word.  Pkg currently assumes the namespace is equal to
the osname and assumes there's a NT_VERSION note defined.  For
correctness, pkg must check that the namespace length is either zero
or equal to an operating system name before …
=> Fix ELF note parsing and recognize NT_GNU_ABI_TAG

configure.ac, libpkg/metalog.c, libpkg/pkg_add.c, libpkg/private/pkg.h
Add metalog entries and don't try to set file flags when the
INSTALL_AS_USER environment variable is set.
This allows me to do
INSTALL_AS_USER=yes pkg -oMETALOG=log -r newworld install FreeBSD-runtime
as a user and have it succeed. Flags are stored in the metalog, and no failures from trying to change flags as a regular user.
=> Support flags when installing as user.

scripts/periodic/410.pkg-audit.in
Right now, periodic pkgaudit scripts only support legacy daily_xxx variables. Add support for more fine grained configuration, like weekly or monthly audit.
=> Support new periodic variable names for pkgaudit

scripts/periodic/460.pkg-checksum.in
Add support of new periodic variable names to 460.pkg-checksum.in as same support is added to 410.pkg-audit.in at 956dcc5f2205168d0ad321b6cc7c25cc473d2314.
=> Add support of new periodic variable names to 460.pkg-checksum.in.

README.md
I re-did the jenkins build and it's better now, so please use this new build status link.
=> Use new jenkins build status link

libpkg/pkg_repo_create.c
As one step towards reproducible builds, ensure that we process directory
entries in deterministic order.
=> Sort fts traversal in repo creation

libpkg/pkg_elf.c
This patch is from wjenkner@inode.at in FreeBSD Bugzilla PR 193995:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=193995
https://bugs.freebsd.org/bugzilla/attachment.cgi?id=147750
=> floating point exception when packaging weird elf files

libpkg/pkg_elf.c
Previously analyse_elf() iterated over the .dynamic section to process
DT_SONAME, DT_RPATH, and DT_RUNPATH, and it exited the loop after
encountering either DT_RPATH or DT_RUNPATH.  This worked only if
DT_SONAME appears before DT_RPATH/DT_RUNPATH.  It appears this is always
true for GNU bfd ld, but not for LLVM's lld linker (which emitted
DT_RUNPATH, DT_NEEDED, then DT_SONAME).
Now, keep track of the DT_RPATH or DT_RUNPATH string while iterating
over .dynamic, but do not exit the loop.
This can probably be simplified further, but initially I want to keep
the same semantics and function call ordering.
FreeBSD PR:	223776
=> Accept DT_SONAME anywhere in .dynamic

src/event.c
When displaying progression, `bdone` contains the number of actions to
action finished, and `nbtodl` and `nbtodl` contains respectively the number
of packages to download and the number of packages to process.
Because `nbtodl` and `nbactions` can have different values, we should check
if we are downloading (progression is `nbdone/nbtodl`) or not (in which
case, the progression is `nbdone/nbactions`).
While here, fix wrapping: when all packages have been downloaded, `nbdone`
is reset to 0, but when processing packages, this condition can happen
again.  So also reset `nbtodl` to 0 to avoid this condition.
=> Fix progression display

scripts/periodic/410.pkg-audit.in, scripts/periodic/460.pkg-checksum.in
Because 410.pkg-audit.in and 460.pkg-checksum.in are not dairy
periodic scripts but security periodic scripts, rename some variables
in them from "dairy_status_security_*" to "security_status_*" to match
them with security periodic scripts in base system. Old
"dairy_status_security_*" variables are still available for backword
compatibility, but waring messages are displayed if they are
explicitly set in /etc/periodic.conf.
=> Rename some variables in security periodic scripts.

libpkg/repo/binary/init.c
Use the correct sqlite3_close method to realy close the database and
avoid open filehandles.
The issue I needed to fix is the open file handle preventing a umount of the partition after installing. But maybe Fixes #1607 too?
=> binary-repo: fix closing sqlite db

libpkg/utils.c
strsep modifies the pointer. Remember and use the pointer returned from strdup
for free.
=> mkdirat_p: fix invalid free

libpkg/pkg_audit.c, src/audit.c, src/upgrade.c
Also assert (return EPKG_FATAL) in pkg_audit_process() if running as
root.
This allows setting /var/db/pkg mode 0750.
=> audit: Drop privileges after opening the files/database but before parsing.

libpkg/utils.c
Pkg will now ask a user to allow OSVERSION mismatch temporarily during repo update. This only affects minor updates (e.g. not something like 11 -> 12, however, the last is also covered by ABI).
=> Improve OSVERSION mismatch check

libpkg/pkg_elf.c
```
... ...
===> Creating FreeBSD-runtime-profile-12.0.s20180114075427
pkg -o ABI_FILE=/usr/obj/usr/src/arm.armv7/worldstage/bin/sh -o ALLOW_BASE_SHLIBS=yes  create -M /usr/obj/usr/src/arm.armv7/worldstage/runtime-profile.ucl  -p /usr/obj/usr/src/arm.armv7/worldstage/runtime-profile.plist  -r /usr/obj/usr/src/arm.armv7/worldstage  -o /usr/obj/usr/src/repo/$(pkg -o ABI_FILE=/usr/obj/usr/src/arm.armv7/worldstage/bin/sh config ABI)/12.0.s20180114075427
===> Creating FreeBSD-runtime-12.0.s20180114075427
pkg -o ABI_FILE=/usr/obj/usr/src/arm.armv7/worldstage/bin/sh -o ALLOW_BASE_SHLIBS=yes  create -M /usr/obj/usr/src/arm.armv7/worldstage/runtime.ucl  -p /usr/obj/usr/src/arm.armv7/worldstage/runtime.plist  -r /usr/obj/usr/src/arm.armv7/worldstage  -o /usr/obj/usr/src/repo/$(pkg -o …
```
=> segmentation fault with strcmp()

libpkg/pkg_jobs_conflicts.c, libpkg/pkg_jobs_universe.c
I'm sure this is not the best way to handle this, but it at least substitutes a crash with an informative error message. I have a hunch that it should be possible to figure out the conflict earlier (at `Checking integrity... done (0 conflicting)`), but that'll require more pkg-foo than I have.
Before:
```
Checking integrity...Child process pid=40754 terminated abnormally:
Segmentation fault
```
After:
```
Checking integrity... done (0 conflicting)
The following 1 package(s) will be affected (of 0 checked):
New packages to be INSTALLED:
vim-console: 8.0.1655 [FreeBSD]
Number of packages to be installed: 1
The process will require 23 MiB more space.
Proceed with this action? [y/N]: y
[dev.ptrcrt.ch] [1/1] Installing vim-console-8.0.1655...
pkg-static: vim-console-8.0.1655 conflicts with …
```
=> Gracefully handle conflicts

docs/pkg-check.8, src/check.c
At least one of the following flags has to be specified: `--shlibs`,
`--dependencies`, `--checksums` and `--recompute`. Similarly, either `--all` or
a *`pattern`* has to be provided. Those command-line parameters are not
optional.
=> Fix usage information for pkg-check

src/annotate.c
All the other commands tend to follow the convention of printing 
an empty line before "For more information see 'pkg help annotate'.
=> Add a missing newline after usage information

docs/pkg-alias.8
* Use Fl instead of Cm for long options.
* Fix typos and style bugs. Pet mandoc -Tlint.
* Add a missing description for the --list flag.
=> Improve pkg-alias.8

src/info.c
This commit fixes `pkg info -R <pkg>` so that YAML is the default raw output
format in all cases when `--raw-format` isn't supplied, not only when
`-F` is being used.
This is based on my understanding of the man page when reading:
```
-R, --raw
Display the full manifest (raw) for the packages matching pkg-name.
--raw-format format
Choose the format of the raw output.  The format can be: json,
json-compact, yaml (default).
```
Which I parsed as "YAML will be the `-R` output unless something else is specified".
=> src/info.c: Make -R behaviour match man page.

src/Makefile.autosetup
Export the same symbols as libpkg.so, so the semi-static pkg can
still load plugins that depend on former libpkg symbols.
=> Export dynamic symbols for plugins.

docs/pkg.conf.5
=> Fix a typo

scripts/periodic/400.status-pkg.in, scripts/periodic/411.pkg-backup.in, scripts/periodic/490.status-pkg-changes.in
Since no supported FreeBSD version has old pkg_* tools in base system anymore, remove hacks for them from periodic scripts.
=> Remove hacks for old pkg_* tools from periodic scripts.

scripts/periodic/410.pkg-audit.in
Since all supported FreeBSD versions have anticongestion function in `/etc/default/periodic.conf`, always use it to insert random sleep with non-interactive mode.
=> Always use anticongestion function in 410.pkg-audit

src/version.c
'pkg version' segfaults when the 'origin' is 'base'.  This patch avoids the crash, however the version for 'base' packages is not determined to be greater-than, lesser-than, or equal-to the latest version available for base packages.
=> Prevent SIGSEGV with 'pkg version' with packaged base.

docs/pkg-upgrade.8
This omission was noticed by tech-lists <tech-lists@zyxst.net> on the freebsd-pkg@ mailing list.
=> Add the standard description of the -x / --regex option to pkg-upgrade(8)

src/updating.c, tests/Makefile.autosetup, tests/frontend/Kyuafile.in, tests/frontend/updating.sh
I added `matcher` function for matching regular expression package names in `AFFECTS:` line.
This function split `AFFECTS:` line into words and each words are checked if it contains regular expression characters or not.
If a word contains regular expression characters, it will be compiled and checked matches to ports origin name.
Compiling a regular expression is relatively slow operation, so I made a cache for compiled objects.
And I added special case of 'AFFECTS: all users' and 'AFFECTS: all ports users'.
The message in these cases should be shown.
This pull request solves [#227193](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=227193) on FreeBSD Bugzilla.
=> make 'pkg updating' to recognize regular expression package names

auto.def, libpkg/pkg_elf.c
Fix a compile error when having the libelf-dev package installed on
debian. This libelf if incompatible to the libelf from elftoolchain as
it has no Elf_Note struct defined.
pkg_elf.c: In function 'analyse_elf':
pkg_elf.c:332:5: error: unknown type name 'Elf_Note'; did you mean 'GElf_Move'?
Elf_Note *en = (Elf_Note *)data->d_buf;
^~~~~~~~
Fix it by checking if Elf_Note is available.
=> auto.def: fix libelf detection on debian

libpkg/Makefile.autosetup, src/Makefile.autosetup
install -s requires the use of correct strip binary when cross
compiling. Since there is no portable way to provide the strip
tool on linux and freebsd remove the strip option and keep debug symbols
if compiled with '-g'.
=> Makefile: do not strip during install

libpkg/pkg_config.c
Close the tested fd and reset the fd variable to -1. Without this a
calling pkg_get_*fd after pkg_close returns a closed fd causing other
operations fail with EBADFD.
=> pkg_config: fix pkg_shutdown

libpkg/pkg_add.c, libpkg/private/pkg.h, tests/frontend/configmerge.sh, tests/frontend/conflicts.sh
but aren't part of any local package, save the current file as .pkgsave
Fixes: 1781
Signed-off-by: Emmanuel Vadot <manu@freebsd.org>
=> When extracting files and they already exists on the local filesystem

src/main.c
There is not necessarily any correlation in version between binaries in a
jail and host OSVERSION, and pkg cannot necessarily tell much from these.
Addresses #1788
=> Suppress version check if -j is specified

docs/pkg-set.8
This was probably copied form `pkg-autoremove`.
=> Fix `-y` documentation for `pkg-set`

libpkg/pkg.h.in
This argument was removed in 59ee42fc074c5687d230dc9ba90f7b91158d4273
=> libpkg: remove non-existent argument

libpkg/pkg.h.in, libpkg/pkg_config.c, src/clean.c
8dd464b255b16 removed the ad-hoc methods of getting the cachedir/cachedirfd in favor of a method in libpkg, but inadvertently left the cachedir itself uninitialized/garbagey. Fix it by adding an accessor for the cachedir name as well, as pkg-clean will at least need/want it for display purposes.
libpkg.ver likely needs regenerated, but there was another change as well when I regenerated it so I deferred for the time being.
=> Fix pkg-clean

libpkg/pkg_add.c, tests/frontend/configmerge.sh
In this case, we can just install the file into the correct location and there's no need to create a .pkgnew.
=> libpkg: don't create .pkgnew if the file didn't exist

libpkg/repo/binary/fetch.c
This fixes a bug which appears to have been introduced by a typo in 8dd464b2 which causes the -o flag in pkg-fetch (custom output directory) to stop working correctly.
This bug affects versions 1.13.0 and 1.13.1 of pkg and causes synth to get "Download failed" errors when "fetch prebuilt packages" is enabled.
=> Fix broken `pkg fetch -o`

scripts/completion/_pkg.in
per pkg-rquery(8):
```
Automatic repository catalogue updates are only attempted when the
effective UID of the process has write access to the package database.
Otherwise they are silently ignored.
```
So when a user that can modify the database attempts completion, they
may experience a delay and think zsh or the system may have locked up.
using zstyle, the automatic updates can be re-enabled.
```
zstyle ':completion:*:pkg*:*:packages' remote-access true
zstyle ':completion:*:pkg-install:*:packages' remote-access true # specifically for a single subcommand
```
=> zsh-completion: disable repo update during package retrival

libpkg/pkg_elf.c
FreeBSD doesn't include the minor version in the ABI; doing so induces some
breakage as this isn't expected.
This fixes up d313276ff3d3d207de to hopefully unbreak -CURRENT package repos.
Signed-off-by: Kyle Evans <kevans@FreeBSD.org>
=> libpkg: fix ABI on FreeBSD

docs/pkg.8
Although it is documented in pkg-info.8, this example might
be helpful to new users who may not feel like browsing
through all the pkg manual pages. `pkg info -D` is one of
the essential commands people need at some point.
Requested by:	Chris <portmaster@BSDforge.com>
=> Add an example of pkg info -D to pkg.8

docs/pkg-create.8, libpkg/libpkg.ver, libpkg/packing.c, libpkg/pkg.h.in, libpkg/pkg_create.c, libpkg/pkg_repo_create.c, libpkg/private/pkg.h, scripts/completion/_pkg.bash.in, scripts/completion/_pkg.in, src/create.c
Add -l, --level option to pkg-create(8) to allow specifying a numeric
compression level to be used with one of the compressing -f,--formats, such as
txz, tzst, or tgz.  (If -f tar is specified, along with a level, this is
considered a usage error.)
This expands the libpkg ABI slightly with the new function
pkg_create_set_compression_level().
Additionally, a member in struct pkg_create was changed to one of a different
size; however, (1) struct pkg_create is carefully not part of the ABI, and (2)
the space was likely consumed by padding bytes anyway, so this change should
not break consumers.
The CLI has two special non-numeric compression levels: fast, and best.  They
do what you would expect.
The API has three sentinel compression levels: INT_MIN (==fast), 0 (default),
and INT_MAX …
=> Fix #1566: Add pkg-create(8) -l,--level to set compression level

libpkg/pkg.h.in, libpkg/pkg_manifest.c, libpkg/repo/binary/update.c
This buffer is eventually passed down to the `pkg_parse_manifest()` function (thus, its corresponding argument should also be constified) and finally to the `ucl_parser_add_chunk()` function which already takes const pointer.  That is, it does not change existing semantics, just self-documents the code better.
=> Constify the buffer passed to pkg_repo_binary_add_from_manifest()

libpkg/pkgdb.c
In the OpenZFS CI we're seeing LOCK_RETRIES is sometimes not exhausted before pkg bails.
I haven't been able to reproduce this locally. Having a debug message here would be helpful.
Sponsored by: iXsystems, Inc.
=> Add a debug message for when obtaining a lock fails

libpkg/lua_scripts.c, libpkg/scripts.c
Note commit a4c28a6 and 0395446 tried to fix the potential hang.  However,
it did not help because poll() does not time out.  See the original patch
set the timeout to 1 second.
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=245462
https://bz-attachments.freebsd.org/attachment.cgi?id=213235
=> Prevent potential hang with scripts (take 2)

tests/frontend/create.sh
Add a missing line continuation that was forgotten in a8bec7220491046b80ba584359491761816f65fb
=> Fix test case list in tests/fronted/create.sh

compat/bsd_compat.h, libpkg/packing.c, mk/common.mk, src/event.c
This fixes linking on macOS which would previously fail with
Undefined symbols for architecture x86_64:
"___unreachable", referenced from:
_packing_set_format in packing.pico
=> Allow building with -Werror=implicit-function-declaration

libpkg/lua_scripts.c, libpkg/scripts.c
I added a new exit case in 722c3a98456b0e4e2bd0aaa8621e6a5fce1cabc6 that
could result in lines being dropped if the child process exits just after
poll timed out. This should hopefully fix the failures on CirrusCI.
=> (lua_)scripts.c: gather remaining output after loop exits

libpkg/pkg_event.c
Fix INFO_NEWPKGVERSION and ERROR_NOLOCALDB emitting invalid JSON.
fixes #1857
=> Fix invalid JSON when EVENT_PIPE is used

src/globals.c, src/pkgcli.h
-fno-common is the default in GCC10 and will also be the default in Clang11.
```
ld: error: duplicate symbol: nbactions
>>> defined at add.c
>>>            add.o:(nbactions)
>>> defined at alias.c
>>>            alias.o:(.bss+0x0)
ld: error: duplicate symbol: nbdone
>>> defined at add.c
>>>            add.o:(nbdone)
>>> defined at alias.c
>>>            alias.o:(.bss+0x4)
ld: error: duplicate symbol: nbtodl
>>> defined at add.c
>>>            add.o:(nbtodl)
>>> defined at alias.c
>>>            alias.o:(.bss+0x8)
ld: error: duplicate symbol: nbactions
>>> defined at add.c
>>>            add.o:(nbactions)
>>> defined at annotate.c
>>>            annotate.o:(.bss+0x0)
ld: error: duplicate symbol: nbdone
>>> defined at add.c
>>>            add.o:(nbdone)
>>> defined at annotate.c
>>> …
```
=> Unbreak build with -fno-common

libpkg/utils.c
=> When the OSVERSION of the new packages is greater, do not default to breaking the user's system.

libpkg/pkg_add.c
=> Correctly detect errors from getpwnam_r and getgrnam_r

libpkg/repo/binary/fetch.c
Fix https://github.com/freebsd/pkg/issues/1807
I believe what is happening is files have been changed and grown slightly. The old good downloads are being appended to which is creating a garbage file, fetch is being set to true, and we're exiting with an error when the checksum comes up wrong.
This change allows to reattempt a full download before giving up.
=> Fix fetch checksum logic

libpkg/pkg_add.c
On my system, getgrnam_r returned ERANGE for a group with a mere 8
members.  RAM is cheap.  Bump the buffer from 128 to 1024 bytes.
=> Use bigger buffers for getpwnam_r and getgrnam_r

libpkg/pkg_elf.c, libpkg/private/elf_tables.h
This adds recognition of EM_RISCV ELF files, and aliases for the
following common ABIs:
- riscv64   (lp64d)
- riscv64sf (lp64)
- riscv32   (ilp32d)
- riscv32sf (ilp32)
On FreeBSD we support riscv64 and its soft-float variant, riscv64sf.
There are no plans to support 32-bit RISC-V at this time, but if we did
this is how I would elect to name it.
This does not attempt to solve the problem of how to name and distribute
packages built with different RISC-V ISA extensions. For now it only
groups based on floating point ABI and ISA width.
The e_flags flags used to determine the float ABI are described in the
RISC-V ELF psABI spec:
https://github.com/riscv/riscv-elf-psabi-doc/blob/master/riscv-elf.md#-file-header
Before:
```
$ ABI_FILE=/usr/obj/usr/home/mitchell/freebsd/riscv.riscv64/usr.bin/unam …
```
=> Add RISC-V ABI aliases

docs/pkg-query.8, libpkg/pkg.c, libpkg/pkg_checksum.c, libpkg/pkg_jobs.c, libpkg/pkg_jobs_universe.c, libpkg/pkg_printf.c, libpkg/pkg_repo_create.c, libpkg/pkgdb.c, libpkg/private/pkg.h, libpkg/private/pkg_printf.h, libpkg/repo/binary/update.c, src/query.c
In addition to the normal checksum used internally we also add the scripts
and lua scripts to the calculation.
This is mostly used for pkgbase where we need to know when only the scripts
have changed to bump the package version.
Signed-off-by: Emmanuel Vadot <manu@FreeBSD.org>
=> query: Add %X to get the internal checksum of the package

docs/Makefile.autosetup, libpkg/Makefile.autosetup, scripts/Makefile.autosetup, src/Makefile.autosetup
Otherwise, if the destination directory does not exist for some reason
we can end up installing a file as the desired directory name.  Now we
will produce an error for the missing directory instead.
=> Add trailing / to install directories

external/libelf/_libelf_config.h, libpkg/pkg_elf.c, libpkg/private/elf_tables.h
Notes:
* The libelf changes are in base already, and I sent them to elftoolchain-devlopers yesterday.
* Needs `-DSQLITE_BYTEORDER=1234` in CFLAGS when building natively due to sqlite3 not detecting powerpc64le currently.
=> Add FreeBSD:13:powerpc64le.

src/create.c
Format string for not overwriting existing package should use
%n for package name, not %s which is for size.
=> Fix misused pkg_printf() format string

auto.def
When git was installed and .git existed but was not usable for some
reason the build failed with a confusing error due to GITHASH being
set to "-fatal: not a git repository: <path>".
Check the return value from git commands and leave GITHASH empty if
non-zero.
Issue #1889
=> Handle error fetching git hash/dirty state

libpkg/lua_scripts.c, libpkg/private/pkg.h, libpkg/scripts.c, tests/frontend/shellscript.sh
@juikim last tried to fix this in #1843.  However, we're still having problems with hangs from pkg when background processes remain and hold `PKG_MSGFD` open.
When I looked at the code in `pkg_run_scripts()`, I found several problems:
* `getline()` is used to read input, this will hang if input is not terminated with LF.
* The code handles the ordering of testing process termination and input availability incorrectly.  If a script starts a daemon that holds `PKG_MSGFD` open and exits, the code will fall into `getline()` and wait forever.
* The `line`/`linecap` variables allocated the input line buffer only once at the start of the loop; longer lines in input after that wouldn't have been completely read by `getline()`.
I reworked the code to check `waitpid()`, then check for input, then …
=> Prevent potential hang with scripts (take 3)

docs/pkg.conf.5
This property has been removed in 792a178d6d33bf711074bd858ea8c486331df1f0.
While here, we might also want to get rid of https://github.com/freebsd/pkg/blob/master/autosetup/system.tcl#L276.
Bugzilla: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=245554
=> Remove autodeps from the example

src/query.c, tests/frontend/query.sh
Here's another thing I found in my repo, which I'd forgotten about:  changes to make `pkg query -F ...` faster.  It does this by setting flags to `pkg_open()` appropriately.  Our build does this...a lot.
=> Faster pkg query -F

libpkg/pkg_add.c
Otherwise, if there's a lua script involved (e.g. @shell), it won't be able
to open any files because rootfd == -1.
This fixes a problem reported doing `pkg upgrade git`.
Signed-off-by: Kyle Evans <kevans@FreeBSD.org>
=> libpkg: open up rootfd for old package cleanup on upgrade

libpkg/Makefile.autosetup, libpkg/scripts.c
I tried CI on MacOS, which found a Mac-specific problem with ECONNRESET, and I saw a potential spin on EAGAIN for all platforms (not sure why this doesn't happen, actually).  Also some minor style cleanup.
=> Fix daemon hang error handling

libpkg/pkg_add.c
Originally, post-install script is executed even when extraction fails. (Is this intended?)
However, it seems that it should only be executed when extract succeeded.
Cleaned up code logic and indentation, now in case of a failed extraction only do the cleanup and rollback on database register. 
Fixes #1885
=> libpkg/pkg_add.c: no execute post-install script when extract fails

libpkg/pkg_elf.c
Downgrade error to warning for elf_begin().
Fixes #1892
=> libpkg/pkg_elf.c: downgrade error to warning 

libpkg/pkg_repo.c, libpkg/repo/binary/update.c
There were two issues here:
1.) pkg_repo_fetch_meta did not handle EPKG_UPTODATE and instead fell back to trying meta.txz -- which failed, because I started using .tzst locally. This fixes #1886, which is the same issue reported by RhToad in #bsdports recently.
2.) If the meta got blown away, we should re-fetch it regardless of the timestamp on the database. The repo update then proceeds as it normally would. I chased my tail on this one for a little bit when I was trying to test the first, because it absolutely refused to re-fetch the meta.conf after I blew it away.
=> Fix fetching of local repo's (file://) meta.conf

libpkg/pkg_checksum.c, libpkg/pkg_create.c, tests/frontend/create.sh
I found two issues:
* a lack of error handling on file reads when checksumming files for a package
* if a file in a manifest was actually a directory, pkg would not catch that, and the above error would cause a SIGBUS
This PR includes tests to show the issues and fixes for them.
=> Fixes for "pkg create" error handling on reading files

libpkg/pkg_create.c
A very minor text-only fixup for #1912.
=> pkg_create.c: minor error message fix

libpkg/pkg_jobs.c, tests/Makefile.autosetup, tests/frontend/upgrade.sh
As described in issue #1881, `pkg upgrade -x '^FreeBSD-kernel'` for instance will attempt to install all of the kernels that I haven't installed locally as well as upgrading any that are out of date. The root of the issue is that pkg_jobs_find_remote_pattern() just checks that we've installed any package that matches the pattern, and pkg_jobs_find_upgrade() would not filter out packages that weren't installed from the initial upgrade query.
Do this now. Newly-added dependencies should still get added as needed as those are pulled in deeper down, rather than at the top-level. The tests demonstrate this.
Fixes #1881
=> pkg-upgrade: don't attempt to install packages matching pattern

docs/pkg-repo.8, libpkg/pkg_repo_create.c, src/repo.c, tests/frontend/pubkey.sh
Stop describing the old format anywhere, prefer that rsa: be specified going forward to ease transition to a world where pkg also accepts, for example, ed25519.
=> pkg-repo: start accepting key files prefixed with "rsa:"

libpkg/pkg_repo_create.c, libpkg/private/utils.h, libpkg/rsa.c
OpenSSL provides envelope methods that let us abstract away the details of
the underlying key. Switch to using these instead of directly using RSA.
This paves the way for making rsa.c a more generic openssl_sign.c that could
easily handle both RSA and ED25519 with minimally invasive changes.
=> libpkg: rsa: start abstracting away rsa bits

src/clean.c
36dfb4895 adjusted the cache logic to use tilde as a separator, which
broke pkg-clean's "latest version" logic. Update pkg-clean to use the
correct separator, but this may be a good candidate for moving to
libpkg.
=> pkg-clean: fix logic for 'latest version'

src/info.c
When processing the right side of a two compare the sign could be
improperly set to the left side sign varible when using <= >= or ==.
=> info: fix info processing of mutliple compares

libpkg/rsa.c
Use pre-1.1 API for builds with LibreSSL
=> libpkg/rsa.c: Fix build with LibreSSL

scripts/periodic/410.pkg-audit.in
security_status_pkgaudit_jails_ignore is a space delimited list of jails
to ignore.
If non-empty, the code iterates over security_status_pkgaudit_jails_ignore
to avoid partial matches (i.e. ignore foo.bar, but not foo). If there is a
better way to do that without looping, please let me know.
=> Allow user to specify ignored jails.

libpkg/pkg_add.c, tests/frontend/add.sh
Currenty either we find the proper version or we go to the
nearest match, but not both, which leads to missing errors
when there is no need for it.
=> pkg-add: provide fallback for version mismatch

libpkg/pkgdb_query.c, libpkg/repo/binary/binary_private.h, libpkg/repo/binary/query.c
Both patches had been part of the previous pull request:
- The condition for passing a parameter for ?1 in an SQL query was wrong. It should be skipped for the MATCH_ALL case even if a condition is specified.
- The attempted fix of the incomplete initializer in libpkg/repo/binary/binary_private.h created a 5 element entry (obvious mis-merge)
=> Two fixes (query -e extension and one mis-merge)

src/utils.c
```
Updating FreeBSD repository catalogue...
Fetching packagesite.pkg: 100%    6 MiB   6.5MB/s    00:01
Processing entries: 100%
FreeBSD repository update completed. 30912 packages processed.
All repositories are up to date.
The following packages will be fetched:
New packages to be FETCHED:
pkg: 1.17.1 (8 MiB: 100.00% of the 8 MiB to download)
Number of packages to be fetched: 1
The process will require 8 MiB more space.
8 MiB to be downloaded.
Proceed with fetching packages? [y/N]: y
Fetching pkg-1.17.1.pkg: 100%    8 MiB   8.7MB/s    00:01
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
Number of packages to be fetched: 1                                    <=========== (expect none)
No packages are required to be fetched. …
```
=> pkg fetch: Don't count cached packages in the fetch count.

scripts/periodic/405.pkg-base-audit.in
Pull request for adding `405.pkg-base-audit.in`  as per your request in this PR 
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=212306#c8
Variable names and format (`$var` vs `${var}`) matches `410.pkg-audit.in` as much as possible but I think both (all) periodic scripts can be cleand up more.
=> Add periodic script 405.pkg-base-audit.in to check vulnerabilities in base system

libpkg/pkg_jobs.c
This fixes a bug hit when updating a pkgbase system. See https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=258357 for some more details.
=> De-prioritize upgrade-removals as well as deletions

libpkg/pkg_jobs_universe.c
This can be reproduced by simply trying to `pkg install` a .pkg out of
/var/cache/pkg.  libpkg ends up blowing up the stack here and crashing,
because it wants to fetch the local package but it's already been presented
with the local package.
Simply stop doing that. This now attempts to install the latest version of
the named packaged from the remote.
=> libpkg: don't recurse on pkg_jobs_universe_process_deps for local pkgs

libpkg/plugins.c
Hi,
I think there is a little error on a variable name in function `pkg_plugin_conf_add` for `type` = `PKG_OBJECT`.
With: `pkg_plugin_conf_add(p, PKG_OBJECT, "KEY", "foo=bar");`
Actual result:
```
"foo=bar" {
}
```
Expected:
```
KEY {
foo = "bar";
}
```
Because variable `key` is overwritten instead of, I guess, (re)using `k`.
=> fix variable name in function pkg_plugin_conf_add for type = PKG_OBJECT

src/search.c, tests/frontend/search.sh
Signed-off-by: Afshin Paydar <afshinpaydar@gmail.com>
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=259696
Using both -q and -o should print only origins without description on the right side, but it prints package names instead:
```
% pkg search -q -o salt
p5-Crypt-Salt-0.01_1
p5-Crypt-SaltedHash-0.09
py38-salt-3004_1
py38-saltyrtc.server-5.0.1_1
rubygem-hammer_cli_foreman_salt-0.0.5
rubygem-smart_proxy_salt-4.0.0
```
=> Fix using search -q -o options together

src/fetch.c
`pkg fetch vim-console` should fail (the package has been renamed to `vim`), but exits with 0 status.
This and many other failure cases were ignored because the `retcode` variable is used for two different purposes, and had been set to 0 earlier.  Fix by adding another variable.
=> pkg-fetch exits with success on many failures; fix

libpkg/pkg_jobs.c, src/install.c, tests/Makefile.autosetup, tests/frontend/add.sh, tests/frontend/create.sh, tests/frontend/fetch.sh, tests/frontend/install.sh
Here's the regression test I promised for `pkg fetch` a couple of weeks ago, plus tests for error cases in `pkg create` and `pkg install`, and fixes for ignored errors in `pkg install` which that found.
`jobs_solve_partial_upgrade()` wasn't returning an error at the right point, so I made it do so.  But I do not claim to fully understand the solver and how jobs work, so someone who does should check my changes.  It does pass all regression tests, but we don't seem to have tests that make the solver work particularly hard.
=> fix `pkg install` error handling, add regression tests

src/Makefile.autosetup
This issue is present on 13.0-RELEASE with latest pkg as well but doesn't
trigger for all TLS certificates.
Updating OPNsense repository catalogue...
Certificate verification failed for /CN=pkg.opnsense.org
34372419584:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/usr/src/crypto/openssl/ssl/statem/statem_clnt.c:1916:
Certificate verification failed for /CN=pkg.opnsense.org
34372419584:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/usr/src/crypto/openssl/ssl/statem/statem_clnt.c:1916:
Certificate verification failed for /CN=pkg.opnsense.org
34372419584:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/usr/src/crypto/openssl/ssl/statem/statem_clnt.c:1916:
Certificate …
=> pkg-static: change library link order to fix validation failures

libpkg/pkg_jobs.c
Updating ser repository catalogue...
ser repository is up to date.
All repositories are up to date.
vulnxml file up-to-date
Checking for upgrades (2 candidates): 100%
Child process pid=99754 terminated abnormally: Segmentation fault
Prevent this segmentation fault by checking that the pointer is not null before
dereferencing.
=> libpkg: Do not dereference NULL pointer

docs/pkg-audit.8
- Sort flags
- Use Fl instead of Cm for flags
- Use Cm for command modifiers
- Break long lines
- Use Dq instead of ``''
- Rewrite the description of the -R flag
- Improve the synopsis of the -R flag
=> Clean up pkg-audit.8

src/pkg.conf.sample
The orphans alias shows installed packages that are not/no longer
in the pkg repo. This find can help finding outdated installed
packages, that have been renamed, removed from the package list,
or were dropped from the repo for other reasons, or by accident.
In a second step this should probably be added to the pkg periodic
scripts.
=> Add orphans alias to pkg.conf.sample

src/which.c
I was running "pkg which" on /usr/local to find unmanaged files and noticed that pkg was consuming a lot more CPU and memory than I expected.  I found that the main loop looks up the package for each file on the commandline, but then pulls the plist for that package.  This data is only needed when both -g and -m options are used.
After changing the code to use the PKG_LOAD_BASIC flag unless PKG_LOAD_FILES is needed, basic calls run much faster and use a fraction of the memory.
Before:
```
$ /usr/bin/time -l pkg which /usr/local/bin/* > /dev/null
11.293 real         9.981 user         1.300 sys
1473208  maximum resident set size
```
After:
```
$ /usr/bin/time -l pkg which /usr/local/bin/* > /dev/null
0.213 real         0.162 user         0.055 sys
62588  maximum resident set size
```
=> speed up plain "pkg which" calls

docs/pkg-repository.5
The pkg-repository manpage claims these are JSON, which isn't accurate.  Describe them better.
=> Improve description of packagesite.txz and filesite.txz file formats.

docs/pkg-lua-script.5
pkg.stat also contains a `type` in the returned `st`.
=> pkg-lua-script.5: document 'type' as return value in pkg.stat

docs/pkg-repository.5
I got the description wrong last time.  Fix.
=> filesite.yaml is simply concatenated, not newline-delimited

.cirrus.yml, auto.def, compat/bsd_compat.h, compat/strnstr.c, external/libfetch/common.c, external/libfetch/fetch.c, external/libfetch/fetch.h, external/libfetch/file.c, external/libfetch/ftp.c, external/libfetch/http.c, libpkg/flags.c, libpkg/pkg.h.in, src/audit.c, src/check.c, src/create.c, src/main.c, src/updating.c
We require support for running pkg on alpine linux. I have picked out the remaining unmerged changes from [q66's](https://github.com/freebsd/pkg/pull/1960) PR, made the remaining requested change to the commits and supplied a cirrus task to test building under alpine so the build status of the code base against libc can be tracked.
Some additional work is still required to get pkg running on alpine as the elfheaders notes in alpine binaries don't contain NT_GNU_ABI_TAG and so we can't get the abi string on runtime.
=> Alpine build support

libpkg/pkg_solve.c
Local system is FreeBSD 12.3. Remote is FreeBSD 13.1.
Ran across this in debug which was confusing:
```
63042:DBG(2)[37457]> solver: require libpkg.so.4: package pkg-1.17.5_1(r) provides wrong ABI freebsd:12:x86:64, wanted freebsd:13:x86:64
...
63045:DBG(2)[37457]> solver: require libpkg.so.4: package pkg-1.17.5_1(r) provides wrong ABI freebsd:12:x86:64, wanted freebsd:13:x86:64
```
Now it makes sense:
```
63042:DBG(2)[7430]> solver: require libpkg.so.4: package pkg-1.17.5_1(r) provides wrong ABI freebsd:13:x86:64, wanted freebsd:12:x86:64
...
63067:DBG(2)[7430]> solver: require libpkg.so.4: package pkg-1.17.5_1(l) provides wrong ABI freebsd:12:x86:64, wanted freebsd:13:x86:64
```
=> solver: Fix backwards debug about remote/local ABI

libpkg/pkg_config.c, src/main.c
I just found these sitting in my repo.  They fix two unimportant memory leaks.  I forget how I identified them exactly, but it was with a compile time or run time memory checker of some sort.
=> Two memory leaks from calls for printf arguments

libpkg/pkghash.c
This fixes a performance regression introduced in 91a326bdf0fb41a3e6a89faec31e9c76b8c3ad5e.
Somebody decided to save a little memory, but when the hash table fills up, the insert code searches the entire table looking for a match or an empty slot.
Seen with `pkg query '%#F' texlive-texmf`, but it was no doubt causing performance regressions in many other places too.
=> Fill hashes to 50%, not 100%.

libpkg/pkg.h.in, libpkg/pkg_config.c, libpkg/private/pkg.h, libpkg/scripts.c, src/main.c
This patch proposes fixing our issue when pkg runs where `/dev/null` is not mounted. @bapt don't hesitate to tell me if the proposed solution is not ok!
close #1763
=> pkg: open dev/null before doing the chroot

docs/pkg.8
As discussed recently in https://www.mail-archive.com/ports@freebsd.org/msg02505.html
add this useful example.
Using `%` as the root's prompt though not sure if this is correct. There are
three different prompts in pkg(8) manual page: `$`, `%` and `#`. In other FreeBSD
documentation `#` seems to be used for root and `%` for user's prompt, while here `%`
seems to be for root and `%` for normal users.
=> pkg(8): Add example on how to restore database.

libpkg/pkg_add.c, libpkg/pkg_delete.c, libpkg/pkg_jobs.c, libpkg/pkgdb_iterator.c, libpkg/pkghash.c, libpkg/private/pkg.h, libpkg/private/pkg_jobs.h, libpkg/repo/binary/query.c, tests/frontend/configmerge.sh
A few minor bug fixes, then a commit which partly addresses FreeBSD PR 263879. The commit itself explains the change.
I would not consider the issue fully solved yet, since we still do not handle the case where a config file participates in a conflict. But, it's enough to fix my pkgbase upgrade problem.
=> First step towards handling config file merges in the face of conflicts

libpkg/pkgdb.c, libpkg/repo/binary/init.c, libpkg/repo/binary/update.c
For basically forever, `pkg` has used SQLite3 with `PRAGMA synchronous = OFF; PRAGMA journal_mode = MEMORY;`, at least during solver execution (which is when the database gets rewritten on package installs).  If pkg or the system crashes then, the database basically _will_ be corrupted.  This changes it to always do `PRAGMA synchronous = FULL; PRAGMA journal_mode = TRUNCATE;`, which is a safe mode that should mostly eliminate corruption.
I put an experimental fix that uses SQLite3 in its optimal mode up as #2009 but we probably don't need to go that far.  #2072 has prompted me to say "let's just fix it already" and this is the result.  Only lightly tested so far; I intend to build `pkg` with this and test it in a system install though.  Performance seems fine in light usage, even on a VM …
=> Use SQLite3 safely

src/main.c
Comes with overhead and does not buy anything as interested parties can instead increase debug. Also note the check was FreeBSD-only.
This effectively reverts 22dcc18a34e689be52b3e07818e2b893efcc03c0
=> Stop checking for being ptrace when starting

libpkg/pkg_config.c
Otherwise, files with NULL in the path are skipped. This is rare, but incorrect nonetheless.
=> Fix incorrect default values for PKG_ARRAY config entries

libpkg/private/utils.h
tempdir name and temp length was erroneously set to MAXHOSTNAMELEN so paths with length greater than 64 were being truncated
This lead to packages failing to install (as shown in the following [issue](https://github.com/freebsd/pkg/issues/2104#issue-1528873214))
=> Fix max temp dir path length

src/check.c
Fix for: https://github.com/freebsd/pkg/issues/2026
=> Fix 'pkg check -q' corrupted output

libpkg/repo/binary/query.c
This is not needed anymore as the table's primary key gets SELECTed.
=> pkg_repo_binary_query: Remove DISTINCT from the SQL query.

docs/pkg-query.8, docs/pkg-rquery.8, src/query.c, src/rquery.c, tests/frontend/query.sh
Issue #2078 was based on a mis-understanding of the semantics of the -i option. It does only apply to pkg-name pattern, not the values inside conditional expressions.
Support for string comparisons that ignore case have been added in a later commit, and thus there is now a way to express such filter conditions.
This commit effectively reverts commits cacd3d7298, c40314fea, and 1bf51ad3ab7 that added the restriction of -e not being allowed in combination with other options and which made the tests that should have warned about the regression match the new reality.
This update should be incorporated into a pkg release as soon as possible, since the current production version of pkg broke the conflicts checks in the ports system ("malke check-copnflicts").
=> Restore support of -e with other options

libpkg/libpkg.ver, libpkg/lua.c, libpkg/pkg.h.in, libpkg/pkg_create.c, libpkg/pkg_jobs.c, libpkg/pkg_repo.c, libpkg/pkg_repo_create.c, libpkg/pkg_repo_update.c, libpkg/pkgdb.c, libpkg/private/event.h, libpkg/private/utils.h, libpkg/repo/binary/fetch.c, libpkg/utils.c
These are changes on the libpkg side that I need to implement a plugin for AppStream metadata fetching. This is a draft and isn't mean to be merged.
To sum it up:
1. I want to have `pkg_repo_fetch_remote_tmp` for a convenient fetching. Without it I have to re-do the logic of making up an url.
2. I need `pkg_emit_error`/`pkg_emit_notice` so that the plugin may report errors and informative messages.
3. It would be great to have access to `mkdirs` and `copy_file`. For now I just copied them into my plugin.
Exporting `pkg_repo_fetch_remote_tmp` isn't probably a right thing to do, so I'll be happy to do it right (rm) way.
=> Changes for the appstream plugin

auto.def
jimtcl allows only one argument to expr
PR: ports/272429
=> fix auto.def:10: Error: wrong # args: should be "expr expression"

libpkg/fetch_libcurl.c
Fixes: e473264a curl: reimplement mirror_type=http
=> fetch_libcurl.c: probable typo (SSL_NO_VERFIRY_PEER)

libpkg/fetch_libcurl.c, libpkg/fetch_ssh.c, libpkg/pkg.h.in, libpkg/pkg_event.c, libpkg/private/event.h
Use this functionality to emit EPKG_NONETWORK when fetchers are unable to connect.
Sponsored by:	Serenity Cybersecurity, LLC
=> Introduce PKG_EVENT_PKG_ERRNO event to report pkg-specific error codes.

libpkg/pkgdb_iterator.c
The recent 204423dced0f30ff6a57031c2086e2bc7a2a0df3 change completely broke `pkgdb_all_search()` use case in PackageKit.
This patch fixes it and also seem to perfectly make sense. I hope it doesn't break anything else.
=> Fix iterating in the pkgdb_all_search(PKGDB_MAYBE_REMOTE) case.

src/main.c
This change makes it possible to add items into PLUGINS field before actually installing these plugins.
=> Make missing plugins a non-fatal warning.

libpkg/fetch_libcurl.c
We avoid complaining for HTTP 304, but let's also not complain if we've failed to fetch entirely (either out of retries or simply cancelled) to reduce the noise a little bit when packages simply haven't been built yet.  More importantly, it avoids leading one to believe that it's perhaps a misconfigured header setting rather than simply missing.
=> libpkg: don't complain about Last-Modified on failed fetches

src/Makefile.autosetup
If etcdir does not exist, we get an error like the following on make install:
install -m 644 /pkg/src/pkg.conf.sample /tmp/foo/etc/
install: target '/tmp/foo/etc/' is not a directory: No such file or directory
I hit this when trying to install with a non-standard prefix.
=> src/Makefile: create etcdir on install

libpkg/Makefile.autosetup
As of lld 17, it has become more strict about undefined symbols in version scripts, leading to errors while linking libpkg.so:
```
ld: error: version script assignment of 'LIBPKG_1.4' to symbol '__progname' failed: symbol not defined
ld: error: version script assignment of 'LIBPKG_1.4' to symbol 'environ' failed: symbol not defined
```
Note that in commit 841c436e these two symbols were explicitly added to libpkg.ver, under the description "Fix issue with recent lld by adding symbols from libcsu", but it is unclear to me which issue that is.
In any case, if these symbols are needed for *some* FreeBSD versions, but not for others, I would like to suggest using the linker option ``--undefined-version``, which stops it from producing errors on undefined versioned symbols, similar to what I …
=> Fix link of libpkg.so with lld >= 17

src/check.c
Not sure if adding it this way (-d[n]) makes sense or if it should be moved to other optional ones.
=> pkg-check: add -n to usage

docs/pkg-repo.8, libpkg/backup_lib.c, libpkg/pkg_add.c, libpkg/pkg_ports.c, libpkg/pkgdb.c
This addresses issue #2182 or at least one instance of it that I hit.
Also included an unrelated, old commit to update pkg-repo documentation.
=> Fix transaction leaks in pkg_add_common()

docs/pkg.8
Graham Perrin reported this typo on bugzilla:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=274291
Fix the syntax for accented char.
=> Fix roff escape sequence for accented char

libpkg/fetch_libcurl.c
A missing libfetch compatibility.
=> fetch_libcurl.c: add support for HTTP_USER_AGENT

libpkg/repo/binary/update.c
Noticed this while working on #2200.  Move the restore into the sanity check to avoid passing a NULL pointer and trying to restore a database that wasn't moved.
=> libpkg: path can be NULL in first cleanup goto

libpkg/utils.c
See commit [message](https://github.com/freebsd/pkg/commit/c1d878bca90216eb10a75134177b61ca501411b9).
=> utils.c: return NULL when getenv(...) fails in get_http_auth() function

libpkg/pkg.h.in, libpkg/pkg_config.c, libpkg/private/pkg.h, libpkg/scripts.c, src/main.c
Used for detecting if running with `pkg --chroot`
=> Introduce PKG_ISCHROOTED script environment variable

docs/pkg.conf.5
d557a86c879a8515d59e8380b083b2265e9a3547
for HTTPS by default was committed to FreeBSD src on 2023-09-11.
=> pkg.conf(5): HTTPS for pkg.freebsd.org

libpkg/fetch.c, libpkg/pkg_elf.c
These changes are a little bigger, I've separated two individual files into two different commits.
First noticed it on this function: libpkg/pkg_elf.c#L1151
=> Avoid multiple calls of strlen() function to calculate the length of a same variable

libpkg/pkg_macho.c
In libpkg/pkg_macho.c, pkg_get_myarch(...) function jumps to a label called "cleanup" whenever either function host_os_info(...) and host_cpu_type(...) don't return EPKG_OK.
Just returning the value whenever one of the functions fails is much more efficient as it avoids the jump and will save a function call, free(...) on NULL (which is practically defined as no operation).
=> libpkg/pkg_macho.c: avoid calling free() and instead just return the error value

libpkg/clean_cache.c
draft (will edit it in a moment).
=> clean_cache.c, backup.c: remove unnecessary return, use goto jumps

libpkg/pkg_jobs.c
I couldn't able to find valid information regarding "mkdirs()" function. Grepping through the source, the only function that's defined called pkg_mkdirs() and not mkdirs(). As pkg_config.h already defines "HAVE_FSTATFS", the content inside the "elif" macro never passes the compiler and gets ignored entirely, otherwise the build would have been failed.
=> libpkg/pkg_jobs.c: use pkg_mkdirs() and not mkdirs()

src/audit.c
The unbracketed statement following the "else" is not indented and appears to be a part of the surrounding code. Fix the whitespace so it is clear that it is part of the conditional.
=> audit: Fix confusing single-line if/else statement

libpkg/backup.c
Whenever copy_database() function fails, it returns a EPKG_FATAL, however, if the function succeed, it returns a SQLITE_OK. Since we already know that we've to return either EPKG_OK or EPKG_FATAL, instead of returning SQLITE_OK, just directly return EPKG_OK. This avoids checking for SQLITE_OK (so we can return EPKG_OK) and the return value of copy_database() can directly be placed.
=> libpkg/backup.c: return error code without an extra check

libpkg/fetch_libcurl.c
Allow user to specify SSL_CA_CERT_PATH in repository configuration environment.
=> curl: Add support for SSL_CA_CERT_PATH env var

libpkg/lua.c
On systems where HAVE_CHFLAGSAT is not defined (Linux) the install_as_user variable is not used. Silence the warning and don't bother calling getenv.
=> lua: Skip unused getenv call and silence unused variable

libpkg/rcscripts.c
s/rcfile/rc/
Signed-off-by: Collin Funk <collin.funk1@gmail.com>
=> rcscripts: Only pass the basename of file to service(8)

libpkg/sha256.c
1. This implementation of SHA-256, doesn't seem like uses memory.h header anywhere except for prototyping memset() but according to POSIX standard, memset() prototype lives inside string.h header and doesn't explicitly say anything for memory.h.
I'm not even sure whether memory.h is in POSIX standard or not (I couldn't find any information regarding this), however, for portability purpose, string.h works better here.
Also, remove the stdlib.h header, it's not being used anywhere in the implementation.
2. Use size_t and not WORD (aka unsigned int). This is because if long is used to define WORD in 16-bit machines, it _may_ overflow as argument len is size_t which is always going to be unsigned.
3. Use static to mark the function sha256_transform(), that's not being used anywhere outside of …
=> libpkg/sha256.c: remove non-standard memory.h header

libpkg/Makefile.autosetup
I found an issue on DragonFly BSD, where pkg builds with the internal libelf, but the installed and packaged libpkg.a doesn't contain the elf_* symbols.
I think it is a fix to 2c1678a commit, maybe just forgot to change the static lib to the flat version.
=> Install the flat version of the static library, to fix consumers

external/blake2/blake2-impl.h
I'm aware that blake2 comes from an external repository, but the official implementation that pkg uses, hasn't seen an update for over 6 years (8 years for pkg repository) and no overall activity for over a year. There's, however, another repository, that implements the same blake2, with additional cleanups, but it also removes some functions (e.g. *16, load16, store16, etc.). Since the current implementation is quite right already, I personally don't think it need to be replaced.
Commit:
https://github.com/freebsd/pkg/commit/475f1e2123bf1dcb1f6a191b964b0cbc82c0b4e5
=> external/blake2: use C99's inline keyword for inlining

.gitignore, src/lock.c
Commit (message): https://github.com/freebsd/pkg/commit/4d0b107a18ac308e39e62260e54b0ed3f4eebf8c
Closes: https://github.com/freebsd/pkg/issues/2211
Also, (I didn't mentioned in the commit message) added
```
/external/libucl/aclocal.m4
/external/libucl/autom4te.cache/
```
in the `.gitignore` file.
=> src/lock.c: return error if package is unavailable to lock/unlock

README.md
Use debian.svg for the debian build (on sourcehut).
=> README.md: use debian SVG for sourcehut build

libpkg/pkgsign_ecc.c
Accidentally included, should have been removed; these don't make any sense in the final context.
=> libpkg: remove some debugging cruft from pkgsign_ecc

libpkg/pkg_solve.c
Remove the "err" jump label as it just being used to return NULL, which can be directly returned (without a jump).
=> libpkg/pkg_solve.c: remove the possibly unused err label

external/libder/README.md, external/libder/libder/libder_obj.c, external/libder/libder/libder_private.h, external/libder/libder/libder_read.c, external/libder/libder/libder_write.c
libder doesn't know whether it's dealing with sensitive material or not, so it now zeroes out every buffer it uses for DER data transport to be overly cautious.
=> external: import libder changes to zero out payloads

external/libder/libder/libder_write.c, libpkg/pkg_repo.c, libpkg/pkg_repo_create.c, libpkg/pkgsign_ossl.c
We shouldn't be reading past the declared size a signer returns, so push the current +/-1 hack that writes/reads a nul terminator into the ossl signer to avoid an overflow in other signers.
=> Fix pkgsign overflow

external/libder/libder/libder_private.h
explicit_bzero() is in <strings.h> on FreeBSD, but <string.h> on Linux -- just include both.
=> external: libder: fix after explicit_bzero() usage

docs/pkg-lock.8, src/lock.c, tests/frontend/lock.sh
Changes on
1. src/lock.c: https://github.com/freebsd/pkg/commit/3428300796864e77b13632277afd40d91f0f1157
2. tests/lock.sh: https://github.com/freebsd/pkg/commit/36316b8c1032f7e1e9a618f7d13319981a3a5ff7
3. docs/pkg-lock.8: https://github.com/freebsd/pkg/commit/353e7e219327a76477726888d5f0ee4557ef027f
=> pkg-lock: add a message if there are no locked packages and fix man page typo

libpkg/elfhints.c
In a FreeBSD 12 environment, the following build errors occur.
elfhits.c needs to include endian.h
```
elfhints.c:457:10: error: implicit declaration of function 'be32toh' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
is_be = be32toh(hdr->magic) == ELFHINTS_MAGIC;
^
elfhints.c:458:6: error: implicit declaration of function 'le32toh' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
if (COND_SWAP(hdr->magic) != ELFHINTS_MAGIC)
^
elfhints.c:72:44: note: expanded from macro 'COND_SWAP'
#define COND_SWAP(n) (is_be ? be32toh(n) : le32toh(n))
^
elfhints.c:458:6: note: did you mean 'be32toh'?
elfhints.c:72:44: note: expanded from macro 'COND_SWAP'
#define COND_SWAP(n) (is_be ? be32toh(n) : le32toh(n))
^
elfhints.c:457:10: note: 'be32toh' declared here
is_be = …
```
=> elfhints.c: include endian.h, copy from pkg_elf.c

libpkg/pkgdb_iterator.c
Reverted this change https://github.com/freebsd/pkg/commit/5edd062df23d708c0dc7c2b58a07de9b38b92a98 otherwise, pkg query won't report packages without licenses when `%L` is used.
See also https://github.com/freebsd/pkg/issues/1510
=> Fix missing packages without license when %L is used

src/utils.c
\* When we issue a command (e.g. pkg install git), to print the
total amount of packages pkg will install, alongside git, it has
to go through all the branches, (used in print_jobs_summary()
function) even though we issued only the install command, so all
other branches will be false.
\* Use putchar('\n') instead of puts(""). Mainly because it just
looks much nicer and explicit than the "trailing newline" (puts)
=> src/utils.c: use else..if for branches, and putchar

docs/pkg_create.3, docs/pkg_repo_create.3
1. [pkg_create.3: fix typo and improve *_set_rootdir line](https://github.com/freebsd/pkg/commit/87e7c9c43a0e3f2859f852853f6996e55df1cdb3)
2. [pkg_repo_create.3: fix typos](https://github.com/freebsd/pkg/commit/5d86571b292cc2581779e40278168e23c4c78664)
=> pkg_create.3, pkg_repo_create.3: fix typos

docs/pkg-create.8
The manual page for pkg-create(8) looked like this:
OPTIONS
The following options are supported by pkg create:
-a, --all         Create package tarballs from all packages installed on
your system.  This option is incompatible with the
-e, --expand-manifest
The manifest contained in pkg will be expanded to
readable UCL format.  -g, -x or -m metadatadir options.
The "expand-manifest" entry was misplaced and just needs to be
moved a bit down.
Reported by: TommyC on EFnet #freebsd
=> pkg-create(8): fix description of --all

libpkg/pkg_jobs.c
This code block is spelled twice in this function and the latter one is more
complete
=> Small cleanup: remove useless code

libpkg/backup.c
In pkgdb_dump(), whenever xstrdup() function is called, it's return value is stored in the d variable. On the next line get_dirname() is called and the return value of it is also stored in the same d variable. Since strdup() does allocate memory, so the previous d pointer for xstrdup() will get lost, resulting a memory leak.
Note: I wasn't able to run the tests apparently.
=> backup.c: do not overwrite the "d" pointer

libpkg/pkg.c
In pkg_open_root_fd() dup() is used to duplicate a file descriptor. However, the on error it prints dup2() (where the error occurred), instead of dup(). This patch changes the function (error message) according to its previous call.
=> pkg.c: change error message from dup2 to dup

src/query.c
String lengths are computed in a for loop, so it will have to call strlen() on each iteration. Although, optimization can store the length in a register, so it won't have to be called on each loop, builds however, with -O0 (optimization off) will not do this.
=> src/query.c: keep the string length in a variable

src/pkg.conf.sample
Where pkgbase is used: without uniq(2), prime-origins will probably list hundreds of identical lines for base.
With one pipe in use, you may as well use a second: sort(1).
=> pkg.conf.sample: pkgbase: prime-origins | sort -u

libpkg/pkg_delete.c
This can happen if the pkg prefix is "/", which is the case for pkgbase packages.
Reported by:	CHERI
=> libpkg: Avoid an out-of-bounds access in pkg_delete_dir()

libpkg/fetch_libcurl.c
Original issue: https://github.com/freebsd/pkg/issues/2302
Note: I cannot test this code, as I am unable to get pkg to use libcurl instead of fetch.  `sudo src/pkg -d -C /usr/local/etc/pkg.conf upgrade` (after building) should suffice, but only seems to leverage libfetch and I don't see a `--flag` for forcing this anywhere.  I clearly see a bunch of stuff in external/libucrl/configure.ac relating to this, and it seems to pick libfetch first due to fetch.h existing -- which makes me wonder why the official FreeBSD pkg binary is using libcurl and not libfetch.  That gets into ports management which I do not want to discuss, period.
=> Improve --debug output when libcurl is used

.clang-format
It is much more convenient to work with the code with automatic style from `clang-format`
=> Add clang-format from the FreeBSD source tree

libpkg/pkg_delete.c
The "pkg->prefix" might be an empty string. Tests do that for example.
=> Fix heap-buffer-overflow found by ASAN

compat/bsd_compat.h
On glibc getprogname() isn't using the `program_invocation_short_name` instead it's using `__progname` global variable. It wasn't checking the existence of `__GLIBC__` macro, so it always falls back to `__progname`, and never went to the glibc part.
=> bsd_compat.h: fix getprogname() to use program_invocation_* on glibc

src/event.c, src/updating.c
Commit messages
1. [src/updating.c: set error code before jumping to out](https://github.com/freebsd/pkg/commit/79575708fb8eb0c4fc0455667c14e9852f2212a5)
2. [src/event.c: free() progress_message only when it's not empty](https://github.com/freebsd/pkg/commit/10b52a95cd550cecdff05b9d88063f6c64a44777)
=> src/{event.c,updating.c}: fix error handling if strdup() fails and some cleanup

libpkg/pkg_jobs.c, libpkg/pkg_jobs_universe.c, libpkg/private/pkg_jobs.h
This function is unused since 1921a4fca.
~~Getting rid of it also allows us to get rid of the inhash field of pkg_job_universe_item as all universe items are now always in universe->items (as one might expect).~~
=> jobs: drop pkg_jobs_universe_change_uid()

libpkg/pkg_jobs.c, libpkg/private/pkg_jobs.h
This pull request simplifies the currently overly complex control flow in pkg_jobs_solve() and pkg_jobs_apply().
There should be no changes to observable behavior of pkg.
I've kept the individual commits small and independent which should hopefully make this patchset easier to review.
=> Simplify pkg_jobs_solve()/pkg_jobs_apply() control flow

libpkg/pkg_add.c, libpkg/pkg_config.c
The introduced MERGETOOL config option expects a value in form "/path/to/program %b %l %r %o" where
* "%b" is the file containing the original config shipped by the previous version of the package
* "%l" is the file containing the current config (%b that is possibly altered by the user)
* "%r" is the new config that is going to be installed by the new package
* "%o" is the file that should be created by the too and contain the merge result
* "%n" is the name of file as listed in the pkg-plist with leading '/' stripped
If the merge tool return a non-zero code, pkg will attempt to the merging using a builtin algorithm.
=> Add support for using external 3-way merge tool when handling @config items

.github/workflows/build.yaml
This is an isolated commit with the GitHub action to build pkg on Ubuntu 22.04/24.04 and MacOS.
The action itself is working, but fails on upstream main as the way we build pkg here (with pkg-config) differs from the way pkg is built elsewhere on Linux, as well as the lack of source code adjustments to build on MacOS.
This pull request is augmenting #2323 and is issued here in isolation to reverse the order (first the build harness, then the patch to fix the build errors).
=> GitHub action to build on Ubuntu 22.04/24.04 and MacOS

libpkg/pkg_create.c, libpkg/pkg_elf.c
This function currently always returns true due to a confusion between the ABI and ALTABI formats.
This can cause issues with automatic shlib provides/requires generation when dealing with e.g. lib32 packages on a 64 bit system.
Note, this does not fully solve https://bugs.freebsd.org/bugzilla//show_bug.cgi?id=265061 as with this patch shlib dependencies will only work properly between "native" (i.e. non-lib32) packages and be completely ignored for lib32 packages. I think that this behavior is still meaningfully less broken than the status quo though.
=> libpkg: fix shlib_valid_abi()

libpkg/pkg_add.c, libpkg/repo/binary/update.c, libpkg/utils.c
Small fixes to improve the codebase.
Major improvement in pkg_add behaviour on MacOS/amd64|arm64. The process crashed due to improper use of strlcpy, with this improvement, 9 kyua tests related to pkg_add pass.
=> Small fixes to improve code, fix crash condition

tests/frontend/fingerprint.sh
The rsa tests execute successfully on MacOS, so make the skip more specific to include them.
=> Enable two more tests on Darwin

compat/bsd_compat.h, tests/lib/checksum.c
On MacOS, AT_FDCWD is defined in sys/fcntl.h. This header was not included by bsd_compat.h an hence it took the liberty to define AT_FDCWD with an arbitrary (wrong) constant.
Error was triggered in tests/checksum:check_files. Improved the call-site to give a verbose error message.
This fixes tests/checksum for MacOS.
=> Fix wrong definition of AT_FDCWD in bsd_compat.h on MacOS.

libpkg/fetch_file.c, tests/frontend/update.sh
pkg handles file:// URLs in libpkg/fetch_file.c which translates the file URL into an access to the local filesystem. Ignoring the host component altogether in this process is semantically wrong. The host component, if given, directs the file to be fetched from that host, not from the local filesystem.
Extend the handling of the host component to accept the localhost host component - the null host component file:/// is anyway accepted already, but reject any other host component, as the code is not intended to go around looking for files on other hosts.
Update the test cases for the changed error message (invalid URL), as well as add a test case for accepting file://localhost/path URL.
closes #2339
=> Fix host component handling in file:// URLs

libpkg/pkg_repo_create.c
MacOS pthread is very sensitive to have phthread mutexes properly initialized, but it should be done everywhere.
With this multi-threaded pkg repo works just fine also on MacOS.
=> Properly initialize phtread mutexes in pkg repo.

libpkg/pkg.h.in, libpkg/pkg_config.c, src/main.c
With pkg using external library dependencies, exact runtime information of these libraries is needed for efficient support.
Add pkg_libversion to libpkg to report its own version. 
Report libpkg, libcurl, libarchive, sqlite and openssl runtime versions in verbose show_version_info() i.e. ```pkg -vv```
=> Add runtime library version information to verbose pkg -vv

tests/frontend/pkg.sh
93928c61477b24d6bbd06b5cff6962cafe1db575 libpkg: switch DEFAULT_VULNXML_URL to HTTPS
changed the default, change the expected value in the testcase to reflect this.
=> Fix failing test after 93928c61477b24d6bbd06b5cff6962cafe1db575 

tests/frontend/abi.sh
Darwin considers amd64 an i386 platform with a x86_64 processor architecture.
The test still fails on Darwin/arm64, but for a better reason.
=> Fix outlier in uname -p on Darwin

.github/workflows/build.yaml, Makefile.autosetup, UndefinedBehaviour.suppress
We maintain a list of suppressions to UndefinedBehaviorSanitizer in order to focus on the work inside pkg.
Structure enables digging into the external code and upstream any fixes.
=> Introduce suppression option to UndefinedBehaviorSanitizer

UndefinedBehaviour.suppress, libpkg/pkgdb.c
Sleeping bug detected by UndefinedBehaviourSanitizer. 
While here, simplify the implementation.
=> Change signature of sqlite getcwd callback function.

tests/frontend/abi.sh
This path was triggered solely on Darwin/aarch64.
=> Yet another small ABI/ALTABI fix.

tests/frontend/fingerprint.sh, tests/frontend/key.sh, tests/frontend/pubkey.sh
openssl on Darwin/aarch64 is pickier than Darwin/amd64i is pickier than FreeBSD.
=> Fix picky openssl.

Makefile.autosetup
Clang Address+Leak Sanitizer behave slightly different on Linux. To actually detect leaks on non-Darwin, ASAN_OPTIONS needs to be set.
This "fixes" the strangely empty ASAN-LSAN runs on MacOS. The traces obtained from Ubuntu are still way more precise, so that platform remains the best to hunt for leaks.
=> Actually detect leaks also on non-Linux

Leak.suppress.in, Makefile.autosetup
LeakSanitizer produces unfixable (from a programmer perspective) leak reports from allocations deep inside system libraries on MacOS. 
Similarly unfixable (from a pkg programmer perspective) leaks are reported against e.g. libcrypto on Ubuntu.
Enable suppression feature for these leaks to focus on actual pkg issues.
This patch makes LeakSanitizer output comparable across MacOS / Linux.
=> Introduce LeakSanitizer suppression

Leak.suppress.in, libpkg/pkg.c, libpkg/pkg_delete.c, libpkg/pkg_jobs_universe.c, libpkg/pkg_manifest.c, libpkg/pkg_repo_create.c, src/updating.c, src/upgrade.c, src/utils.c
Mostly detected by LeakSanitizer, but also extended to recurring patterns like not freeing buffer after getline or getmode.
=> Final round of low hanging leaks.

libpkg/pkg_config.c
These have been unused since 2014 (99f9cd1a2c).
=> libpkg: remove unused descriptions in pkg_config.c

libpkg/pkg_config.c
Commit 9df5da58d which aimed to only removed dead code accidentally deleted the default value for VALID_URL_SCHEME.
My text editor magic failed me as this option lacked a description even before 9df5da58d.
This commit fixes the regression.
=> libpkg: fix regression in config parsing

UndefinedBehaviour.suppress.in, external/picosat/picosat.c
Suggested fix was reported to Prof. Biere by email.
=> Fix external/picosat undefined behaviour.

libpkg/pkg_abi.c, libpkg/pkg_abi_macho.c, libpkg/private/pkg_abi.h
pkg uses the OS, which under MacOS is Darwin. Rename PKG_OS_MACOS to PKG_OS_DARWIN to be consistent in the source as well.
Cater for a corner case in having a basename in Mach-O dynamic library.
Adjust comments and simplify parsing code in pkg_abi_macho after the major abi refactoring.
=> Consistently use Darwin and other cosmetics

libpkg/pkg_abi.c, tests/frontend/abi.sh, tests/frontend/create-parsebin.sh, tests/frontend/test_environment.sh.in
The new improved ABI code is specific about amd64 vs. x86_64 naming.
Darwin in fact uses x86_64 (uname -m produces x86_64).
Adjust the code as well as the test cases to use this value instead of the previously chosen amd64.
=> Consistently name x86_64 on Darwin

libpkg/private/pkgdb.h
These functions were removed years ago but the declarations in the pkgdb.h header were forgotten.
=> libpkg: remove declarations of dead functions

Leak.suppress.in, libpkg/fetch_libcurl.c, libpkg/pkg.c, libpkg/pkg_add.c, libpkg/pkg_config.c, libpkg/pkg_jobs.c, libpkg/pkg_manifest.c, libpkg/pkgdb_iterator.c, libpkg/pkgvec.h, libpkg/ssh.c, libpkg/triggers.c, src/clean.c, src/main.c, src/query.c, src/updating.c, tests/lib/checksum.c, tests/lib/lua.c, tests/lib/packing.c, tests/lib/pkg_elf.c, tests/lib/plist.c, tests/lib/ssh.c, tests/lib/utils.c, tests/lib/vec.c
Skip known not to work elfparsing on Linux/Ubuntu.
Instead of 200 failing/broken tests in ASAN/LSAN runs, prepare a list of ~20 exclusions which cause memory leaks.
Fix along the way another dozen of leaks.
The list of exclusions is considered to be better, as you can decide to work on one at a time. Clearing out the list. Note that some of the exclusions cover heavily used core code paths.
Having no errors in ASAN/LSAN runs enables to trigger errors when NEW leaks are introduced into the codebase, hence stopping the rot.
Note that atf-0.22 pretty much broke kyua/atf on MacOS, the MacOS CI runs take infinite time. Ubuntu is still fine (on 0.21).
=> Prepare for sanitizer runs to fail hard during CI

.github/workflows/build.yaml
After removing all "known" errors and failures even in the sanitized runs, make the CI build fail expressively and visually if any new check is missed.
While here
* combine ubsan/tsan runs to have overall less runs.
* prepare for ubuntu-latest to become ubuntu-24.04
* beautify kyua results in Action summary
* report kyua version in logs
* include raw-text as well as junit formatted results in build artefact
* include kyua logs in build artefact
=> Improve CI build, fail on checks

libpkg/pkg.c, libpkg/pkg_abi_macho.c, libpkg/pkg_config.c, libpkg/pkg_elf.c, libpkg/pkg_manifest.c, libpkg/pkgdb_iterator.c, libpkg/private/pkg.h, libpkg/system_shlibs.c, tests/frontend/test_environment.sh.in, tests/lib/pkg_elf.c
When scanning ELF files to generate the shlibs_provided/required lists, pkg now generates entries for lib32 and Linux compat shlibs rather than ignoring all non-native shlibs.
The following format is used for shlibs_provided/required entries:
```
libfoo.so.1.0.0          - native (no change to status quo)
libfoo.so.1.0.0:32       - compat 32
libfoo.so.1.0.0:Linux    - compat Linux
libfoo.so.1.0.0:Linux:32 - compat Linux 32
```
This is only done if targeting FreeBSD for now.
I've marked this as a draft because it depends on the unmerged #2386 and because I would like to add more tests before it is merged.
References: https://github.com/freebsd/pkg/issues/2331
=> libpkg: track lib32 and Linuxulator shlibs 

compat/bsd_compat.h
GCC has _\_GNUC_MINOR\_\_ set to 2 (from godbolt). As it was detecting a specific version of it, __builtin_unreachable() was never being used with GCC (as _\_GNUC_MINOR\_\_ < 6). From godbolt, it looks like __builtin_unreachable() was introducued somewhere between 4.4.7 to 4.5.3. These versions were released back in 2011, so I think it's safe to assume that most systems have at least 4.5 or higher.
For Clang, __builtin_unreachable() (from godbolt test), available since at least 3.0, which was released in 2011 as well.
=> bsd_compat.h: fix __builtin_unreachable() detection with GCC

.github/workflows/build.yaml, Leak.suppress.in
In order to benefit the changes in ```atf```, temporarily use HEAD.
While here, use macos-15 runner and clean up YAML. 
Add suppressions for newly introduced MacOS system library functions, there are way too many!
Left 3 tests failing as they look very interesting -- memory poisoning in lua. Perhaps somebody is attracted to fixing them.
=> Use atf --HEAD on MacOS

libpkg/Makefile.autosetup
Single change needed to successfully cross-compile on macOS to FreeBSD.
=> Use $(AR) instead of hardcoding ar tool

docs/pkg-create.8
As noted in FreeBSD PR 284054 users may expect -f to set the output package's extension, but it is (now) always .pkg.  Try to clarify by using "comrpession format" and explicitly noting that the extension is .pkg.
=> pkg-create.8: Clarify -f (compression format)

libpkg/pkg_config.c
Do an initial parse of pkg.conf without any variable expansion that only reads variables that can affect the ABI before determining ctx.abi.
=> libpkg: allow configuring ABI in pkg.conf 

.github/workflows/build.yaml, Leak.suppress.in, src/main.c, tests/frontend/pkg.sh, tests/lib/lua.c
* Filter through suppressions and check if still relevant
* Tighten suppressions to match more specific functions
* Fix memory leak in show_version_info
* Fix pkg invocation with overriden environment to use all sanitizer options (incl. suppressions)
* Investigate and eventually disable reported Lua poisoning
=> Review leak suppression

.gitignore, libpkg/pkg.c, libpkg/pkg_abi.c, libpkg/pkg_abi_macho.c, libpkg/pkg_config.c, libpkg/pkg_elf.c, libpkg/private/binfmt.h, libpkg/private/utils.h, libpkg/utils.c, tests/frontend/create-parsebin.sh, tests/lib/pkg_elf.c, tests/lib/utils.c
This branch adds several useful ways to filter the shared libraries automatically added to `shlibs_provided` by a pkg based on parsing the ELF/Mach-O binary. These two commits are the most relevant:
```
libpkg: add SHLIB_PROVIDE_PATHS_* options
This allows limiting the files in a package that can affect
shlibs_provided when ELF files are scanned during e.g. pkg create.
The ports system will be able to populate these options automatically
based on the already existing USE_LDCONFIG variable.
```
```
libpkg: add SHLIB_PROVIDE_IGNORE_{GLOB,REGEX} options
These are quite simple to implement and nicely complement the
SHLIB_REQUIRE_IGNORE_{GLOB,REGEX} options.
```
=> libpkg: allow filtering provided shlibs

src/main.c, tests/frontend/pkg.sh
Currently, this causes pkg to exit with the very unhelpful error message
"pkg: unknown command: bootstrap"
This used to have the same behavior as `pkg bootstrap`in older versions
of pkg prior to commit https://github.com/freebsd/pkg/commit/fb9b33123ca608de0919fdcd3df6b43202dd4bf2.
This commit restores the old behavior of `pkg bootstrap -y` and does not
affect the behavior if `-f` is passed.
References: https://github.com/ifreund/pkgbasify/issues/6
=> src: fix pkg bootstrap -y

docs/pkg.conf.5
I think we need the kmods repo in the reference manual. Some things to note:
1. I'm running current for a years and don't know if the syntax is correct, I copied this from helpdesk-chat on Community Discord.
2. $dayjob asks the first commit in a repo to use my work mail address.
3. I cannot send this patch unless the license is standard open source, which it is not since it's currently truncated. I selected what I thought was most reasonable, I put the copyright in the name of the project, like style(9) (perhaps someone else needs to do this part because of my $dayjob), but if something else is more appropriate, no problem. I actually prefer just SPDX tag but that seems like a separate issue.
Thanks!
=> pkg.conf.5: Mention kmods repo + fix copyright

libpkg/pkg_config.c, tests/frontend/config.sh
These require absolute paths, providing a relative path currently triggers an assertion failure. This commit adds validation of these options and test cases to prevent regression.
Fixes:		a35c0a302ad8
=> libpkg: validate SHLIB_PROVIDE_PATHS_* options

docs/pkg.8
`pkg -vv` has been important for helping users with the kmods issue. Note it in the manual.
Can someone other than me please fix the license on all the manuals so I can work on them comfortably? Copyright and license makes me very nervous because of $dayjob.
Since the pkg project has a perfectly good license, I do not think these files even need their own license statement, but since they have one, I think it can not be truncated.
I did ask core and learned license without copyright is okay, so this only adds the truncated text back to the bottom.
=> pkg.8: Mention -vv + fix license

external/libcurl/Makefile.autosetup, libpkg/Makefile.autosetup, src/Makefile.autosetup
Add missing file and libraries required by curl.
Resolves:
```
Undefined symbols for architecture arm64:
"_Curl_macos_init", referenced from:
_curl_global_init in libcurl_pic.a[18](easy.pico)
_curl_global_init_mem in libcurl_pic.a[18](easy.pico)
_curl_easy_init in libcurl_pic.a[18](easy.pico)
```
```
Undefined symbols for architecture arm64:
"_CFRelease", referenced from:
_Curl_macos_init in libcurl_pic.a[39](macos.pico)
"_SCDynamicStoreCopyProxies", referenced from:
_Curl_macos_init in libcurl_pic.a[39](macos.pico)
"_inflate", referenced from:
_inflate_stream in libcurl_pic.a[11](content_encoding.pico)
"_inflateEnd", referenced from:
_deflate_do_write in libcurl_pic.a[11](content_encoding.pico)
_deflate_do_close in libcurl_pic.a[11](content_encoding.pico)
_inflate_stream in …
```
=> Fix build on macOS

libpkg/backup_lib.c
We are calling pkg_open_root() early but if strrchr() is NULL, then it's not executing the body anyway, so check the strrchr() condition before open_root.
Also, zero initialize the buffer. (valgrind warning).
=> backup_lib.c: call strrchr() before pkg_open_root and memset

libpkg/pkg_add.c
When a pkg has multiple configuration files, it's nice to be able to identify the failure at a glance.
=> libpkg: add the path when we fail to do a 3way merge

src/check.c
It is allocated using `pkgdb_query` a few lines up.
This stops `sqlite3_close` from returning `SQLITE_BUSY` when closing.
The warning message can be reproduced by attempting to check a non-existent package, e.g `pkg check nonexistent`.
=> check: fix iterator leak

libpkg/packing.c
When pkg installs a package, it uses the embedded uname/gname to set the owner/group for an extracted file; see get_uid_from_archive() and get_gid_from_archive() in pkg_add.c.  However, the tar format also stores a numeric uid/gid, and if not specified, it's set to the current user's uid/gid.
This means unprivileged user-created packages (e.g., pkgbase packages) might have reproducibility issues if we compare packages built by different users.
Fix this by hard-coding a harmless, fixed value for the numeric uid/gid on FreeBSD.  We could alternately just set the uid/gid to 0/0.
Sponsored by:	Klara, Inc.
=> libpkg: Set numeric uid/gid when adding archive entries

docs/pkg-create.8
Discussed with @bsdbcr, the precedence seems to be that the capital letter options should be before the lowercase options.
=> Sort pkg-create(8) options

docs/pkg-repositories.8
+ tag spdx, add truncated section of license
+ add "package" to document description for apropos
+ improve introductory sentence specificity
+ correct duplicated -d in options
+ normalize files, pad and remove prompts from examples
+ trivial minor mdoc nits
PR: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=288366
=> pkg-repositories.8: Minor cleanup

docs/pkg-lua-script.5, docs/pkg-script.5, libpkg/lua_scripts.c, libpkg/pkg_config.c, libpkg/private/pkg.h, libpkg/scripts.c
This is useful for non-root package installations.  For instance, the pkg post-install and post-deinstall for ca_root_nss just runs "certctl rehash", but certctl can take a METALOG path parameter.  With this feature and a bit of work, that post-install script can be run as a non-root user.
=> libpkg: Provide the METALOG path to pkg scripts

src/check.c
Free the iterator when we are done using it, preventing more leaks when we goto cleanup.
Also replace the cleanup label with a break.
Noticed by: kevans
=> check: plug more iterator leaks

docs/pkg.8
pkg(8) should document the local archive capability of pkg-install(8).
=> pkg(8) COMMANDS: install: local archive

tests/lib/pkg_osvf.c
Ubuntu 20.04 have old ATF which does not have ATF_CHECK_INTEQ macro. Change test to use pure ATF_CHECK.
=> tests: Fix OSVF test building on Ubuntu 20.04

.gitignore, libpkg/pkg.c, libpkg/pkgdb_iterator.c, libpkg/private/utils.h, tests/Makefile.autosetup, tests/frontend/abi.sh, tests/frontend/check.sh, tests/frontend/config.sh
Plus some assorted cleanups and a new regression test.
=> Fix `pkg -r <rootdir> check`

Makefile.autosetup, libpkg/pkg_abi.c, libpkg/pkg_jobs.c, libpkg/pkg_jobs_universe.c, libpkg/pkgdb_iterator.c, libpkg/private/pkg_jobs.h
The next PR will contain some actual functional changes. Just submitting these separately in advance.
=> libpkg cleanups

docs/pkg-query.8, docs/pkg_printf.3, libpkg/pkg.c, libpkg/pkg_add.c, libpkg/pkg_create.c, libpkg/pkg_manifest.c, libpkg/pkg_ports.c, libpkg/pkg_printf.c, libpkg/pkgdb.c, libpkg/pkgdb_iterator.c, libpkg/private/db_upgrades.h, libpkg/private/pkg.h, libpkg/private/pkg_printf.h, src/query.c, tests/frontend/create-parsebin.sh, tests/frontend/create.sh, tests/frontend/query.sh, tests/frontend/test_environment.sh.in
and allow pkg-query to list those attributes using new format specifiers.
The idea is to embed the file and directory metadata (user, group, permissions, file flags) during package creation time in +MANIFEST. Later, this metadata will be written into the package database during install time. Support for querying metadata is provided in this patch.
This patch does not change the way which metadata is used during installation time. The metadata used during package installation still relies on the tar embedded metadata (which should be equal to the metadata in the +MANIFEST, but we don't verify this yet).
Partially addresses #1088 and allows to implement a metadata aware pkg-check later.
=> pkgdb: track uname, gname, permissions and fflags in pkgdb
